// Hand-curated column-level lineage graphs for the seven anchor subdomains.
// Each graph follows a six-column layout:
//   0: Source systems
//   1: Staging
//   2: Vault hubs / links
//   3: Vault satellites
//   4: Marts (star)
//   5: KPIs
// The diagram component (`components/lineage-diagram.tsx`) renders any of these.
//
// Names are pulled from the corresponding YAML in `data/taxonomy/<anchor>.yaml`
// and the DDL in `modeling/ddl/<anchor>_*.sql`. The intent is realism, not
// exhaustive coverage — about 30 nodes per anchor scans cleanly at desktop
// width and remains scrollable on mobile.

export type LineageKind = "source" | "stage" | "vault" | "mart" | "kpi";

export interface LineageNode {
  id: string;
  label: string;
  sub?: string;
  layer: number; // column index 0..5
  row: number; // row index 0..n
  kind: LineageKind;
}

export interface LineageEdge {
  from: string;
  to: string;
}

export interface LineageGraph {
  title: string;
  vertical: string;
  oneLiner: string;
  nodes: LineageNode[];
  edges: LineageEdge[];
}

export const ANCHOR_KEYS = [
  "payments",
  "p_and_c_claims",
  "merchandising",
  "demand_planning",
  "hotel_revenue_management",
  "mes_quality",
  "pharmacovigilance",
  // Wave 2 — the 10 new anchors. Names match the corresponding YAML id and
  // the schema prefix used by their SQL DDL (e.g. ehr_integrations_vault.*).
  "ehr_integrations",
  "capital_markets",
  "smart_metering",
  "clinical_trials",
  "cloud_finops",
  "ev_charging",
  "tax_administration",
  "real_world_evidence",
  "settlement_clearing",
  "programmatic_advertising",
] as const;

export type AnchorKey = (typeof ANCHOR_KEYS)[number];

// ---------------------------------------------------------------------------
// payments
// ---------------------------------------------------------------------------

const payments: LineageGraph = {
  title: "Payments",
  vertical: "BFSI",
  oneLiner:
    "Money movement across cards, ACH, wires, and real-time rails — auth, clearing, settlement, and dispute handling end-to-end.",
  nodes: [
    // sources
    { id: "src.stripe", label: "Stripe", sub: "Acquirer/PSP", layer: 0, row: 0, kind: "source" },
    { id: "src.temenos", label: "Temenos Transact", sub: "Core Banking", layer: 0, row: 1, kind: "source" },
    { id: "src.fis", label: "FIS Profile", sub: "Core Banking", layer: 0, row: 2, kind: "source" },
    { id: "src.aci", label: "ACI EPS", sub: "Payments Hub", layer: 0, row: 3, kind: "source" },
    { id: "src.swift", label: "SWIFT Alliance", sub: "Messaging", layer: 0, row: 4, kind: "source" },
    // staging
    { id: "stg.payments", label: "stg_payments__payments", sub: "view", layer: 1, row: 0, kind: "stage" },
    { id: "stg.settle", label: "stg_payments__settlements", sub: "view", layer: 1, row: 1, kind: "stage" },
    { id: "stg.cb", label: "stg_payments__chargebacks", sub: "view", layer: 1, row: 2, kind: "stage" },
    { id: "stg.cust", label: "stg_payments__customers", sub: "view", layer: 1, row: 3, kind: "stage" },
    { id: "stg.merch", label: "stg_payments__merchants", sub: "view", layer: 1, row: 4, kind: "stage" },
    // vault hubs & links
    { id: "vault.h_payment", label: "hub_payment", sub: "Vault hub", layer: 2, row: 0, kind: "vault" },
    { id: "vault.h_customer", label: "hub_customer", sub: "Vault hub", layer: 2, row: 1, kind: "vault" },
    { id: "vault.h_merchant", label: "hub_merchant", sub: "Vault hub", layer: 2, row: 2, kind: "vault" },
    { id: "vault.l_pc", label: "link_payment_customer", sub: "Vault link", layer: 2, row: 3, kind: "vault" },
    { id: "vault.l_pm", label: "link_payment_merchant", sub: "Vault link", layer: 2, row: 4, kind: "vault" },
    // vault sats
    { id: "vault.s_payment", label: "sat_payment", sub: "Vault sat", layer: 3, row: 0, kind: "vault" },
    { id: "vault.s_settle", label: "sat_settlement", sub: "Vault sat", layer: 3, row: 1, kind: "vault" },
    { id: "vault.s_cb", label: "sat_chargeback", sub: "Vault sat", layer: 3, row: 2, kind: "vault" },
    { id: "vault.s_cust", label: "sat_customer", sub: "Vault sat", layer: 3, row: 3, kind: "vault" },
    { id: "vault.s_merch", label: "sat_merchant", sub: "Vault sat", layer: 3, row: 4, kind: "vault" },
    // marts
    { id: "mart.fct_payments", label: "fct_payments", sub: "fact (table)", layer: 4, row: 0, kind: "mart" },
    { id: "mart.fct_settle", label: "fct_settlements", sub: "fact (table)", layer: 4, row: 1, kind: "mart" },
    { id: "mart.fct_cb", label: "fct_chargebacks", sub: "fact (table)", layer: 4, row: 2, kind: "mart" },
    { id: "mart.dim_cust", label: "dim_customer", sub: "dim (table)", layer: 4, row: 3, kind: "mart" },
    { id: "mart.dim_merch", label: "dim_merchant", sub: "dim (table)", layer: 4, row: 4, kind: "mart" },
    // KPIs
    { id: "kpi.stp", label: "STP Rate", sub: "pay.kpi.stp_rate", layer: 5, row: 0, kind: "kpi" },
    { id: "kpi.lat", label: "Settlement Latency", sub: "pay.kpi.settlement_latency", layer: 5, row: 1, kind: "kpi" },
    { id: "kpi.cb", label: "Chargeback Ratio", sub: "pay.kpi.chargeback_ratio", layer: 5, row: 2, kind: "kpi" },
    { id: "kpi.afr", label: "Auth Failure Rate", sub: "pay.kpi.afr", layer: 5, row: 3, kind: "kpi" },
    { id: "kpi.ic", label: "Interchange Revenue", sub: "pay.kpi.interchange_revenue", layer: 5, row: 4, kind: "kpi" },
  ],
  edges: [
    { from: "src.stripe", to: "stg.payments" },
    { from: "src.aci", to: "stg.payments" },
    { from: "src.aci", to: "stg.settle" },
    { from: "src.swift", to: "stg.settle" },
    { from: "src.temenos", to: "stg.cb" },
    { from: "src.fis", to: "stg.cust" },
    { from: "src.temenos", to: "stg.cust" },
    { from: "src.stripe", to: "stg.merch" },
    { from: "stg.payments", to: "vault.h_payment" },
    { from: "stg.payments", to: "vault.s_payment" },
    { from: "stg.cust", to: "vault.h_customer" },
    { from: "stg.cust", to: "vault.s_cust" },
    { from: "stg.merch", to: "vault.h_merchant" },
    { from: "stg.merch", to: "vault.s_merch" },
    { from: "stg.settle", to: "vault.s_settle" },
    { from: "stg.cb", to: "vault.s_cb" },
    { from: "vault.h_payment", to: "vault.l_pc" },
    { from: "vault.h_customer", to: "vault.l_pc" },
    { from: "vault.h_payment", to: "vault.l_pm" },
    { from: "vault.h_merchant", to: "vault.l_pm" },
    { from: "vault.s_payment", to: "mart.fct_payments" },
    { from: "vault.l_pc", to: "mart.fct_payments" },
    { from: "vault.l_pm", to: "mart.fct_payments" },
    { from: "vault.s_settle", to: "mart.fct_settle" },
    { from: "vault.s_cb", to: "mart.fct_cb" },
    { from: "vault.s_cust", to: "mart.dim_cust" },
    { from: "vault.s_merch", to: "mart.dim_merch" },
    { from: "mart.fct_payments", to: "kpi.stp" },
    { from: "mart.fct_payments", to: "kpi.afr" },
    { from: "mart.fct_settle", to: "kpi.lat" },
    { from: "mart.fct_cb", to: "kpi.cb" },
    { from: "mart.fct_payments", to: "kpi.ic" },
  ],
};

// ---------------------------------------------------------------------------
// p_and_c_claims
// ---------------------------------------------------------------------------

const pAndCClaims: LineageGraph = {
  title: "P&C Claims",
  vertical: "Insurance",
  oneLiner:
    "FNOL through closure for property & casualty claims — assignment, reserves, payouts, and recovery, with bitemporal reserve history.",
  nodes: [
    { id: "src.gw", label: "Guidewire ClaimCenter", sub: "Claims Platform", layer: 0, row: 0, kind: "source" },
    { id: "src.dc", label: "Duck Creek Claims", sub: "Claims Platform", layer: 0, row: 1, kind: "source" },
    { id: "src.sf", label: "Salesforce FSC", sub: "Customer 360", layer: 0, row: 2, kind: "source" },
    { id: "src.ir", label: "ImageRight", sub: "Claims Docs", layer: 0, row: 3, kind: "source" },
    { id: "src.iso", label: "ISO ClaimSearch", sub: "Industry Data", layer: 0, row: 4, kind: "source" },
    { id: "stg.claims", label: "stg_claims", sub: "view", layer: 1, row: 0, kind: "stage" },
    { id: "stg.policies", label: "stg_policies", sub: "view", layer: 1, row: 1, kind: "stage" },
    { id: "stg.adjusters", label: "stg_adjusters", sub: "view", layer: 1, row: 2, kind: "stage" },
    { id: "stg.fnol", label: "stg_fnol_events", sub: "view", layer: 1, row: 3, kind: "stage" },
    { id: "stg.payouts", label: "stg_claim_payments", sub: "view", layer: 1, row: 4, kind: "stage" },
    { id: "vault.h_claim", label: "hub_claim", sub: "Vault hub", layer: 2, row: 0, kind: "vault" },
    { id: "vault.h_policy", label: "hub_policy", sub: "Vault hub", layer: 2, row: 1, kind: "vault" },
    { id: "vault.h_adj", label: "hub_adjuster", sub: "Vault hub", layer: 2, row: 2, kind: "vault" },
    { id: "vault.l_cp", label: "link_claim_policy", sub: "Vault link", layer: 2, row: 3, kind: "vault" },
    { id: "vault.l_ca", label: "link_claim_adjuster", sub: "Vault link", layer: 2, row: 4, kind: "vault" },
    { id: "vault.s_cstate", label: "sat_claim_state", sub: "Vault sat", layer: 3, row: 0, kind: "vault" },
    { id: "vault.s_reserve", label: "sat_claim_reserve_bitemporal", sub: "Vault sat (bitemporal)", layer: 3, row: 1, kind: "vault" },
    { id: "vault.s_pol", label: "sat_policy_descriptive", sub: "Vault sat", layer: 3, row: 2, kind: "vault" },
    { id: "vault.s_phold", label: "sat_policyholder_descriptive", sub: "Vault sat", layer: 3, row: 3, kind: "vault" },
    { id: "vault.s_pay", label: "sat_payout_state", sub: "Vault sat", layer: 3, row: 4, kind: "vault" },
    { id: "mart.fct_claim", label: "fact_claim_event", sub: "fact (table)", layer: 4, row: 0, kind: "mart" },
    { id: "mart.fct_pay", label: "fact_claim_payment_daily", sub: "fact (daily)", layer: 4, row: 1, kind: "mart" },
    { id: "mart.fct_tri", label: "fact_loss_triangle", sub: "fact (table)", layer: 4, row: 2, kind: "mart" },
    { id: "mart.dim_pol", label: "dim_policy", sub: "dim (SCD2)", layer: 4, row: 3, kind: "mart" },
    { id: "mart.dim_adj", label: "dim_adjuster", sub: "dim (table)", layer: 4, row: 4, kind: "mart" },
    { id: "kpi.cycle", label: "Claim Cycle Time", sub: "pcc.kpi.cycle_time", layer: 5, row: 0, kind: "kpi" },
    { id: "kpi.leak", label: "Claims Leakage", sub: "pcc.kpi.leakage", layer: 5, row: 1, kind: "kpi" },
    { id: "kpi.sev", label: "Severity", sub: "pcc.kpi.severity", layer: 5, row: 2, kind: "kpi" },
    { id: "kpi.freq", label: "Frequency", sub: "pcc.kpi.frequency", layer: 5, row: 3, kind: "kpi" },
    { id: "kpi.lae", label: "LAE Ratio", sub: "pcc.kpi.lae_ratio", layer: 5, row: 4, kind: "kpi" },
  ],
  edges: [
    { from: "src.gw", to: "stg.claims" },
    { from: "src.dc", to: "stg.claims" },
    { from: "src.gw", to: "stg.fnol" },
    { from: "src.gw", to: "stg.payouts" },
    { from: "src.dc", to: "stg.policies" },
    { from: "src.sf", to: "stg.policies" },
    { from: "src.sf", to: "stg.adjusters" },
    { from: "src.ir", to: "stg.fnol" },
    { from: "src.iso", to: "stg.claims" },
    { from: "stg.claims", to: "vault.h_claim" },
    { from: "stg.claims", to: "vault.s_cstate" },
    { from: "stg.payouts", to: "vault.s_reserve" },
    { from: "stg.policies", to: "vault.h_policy" },
    { from: "stg.policies", to: "vault.s_pol" },
    { from: "stg.policies", to: "vault.s_phold" },
    { from: "stg.adjusters", to: "vault.h_adj" },
    { from: "stg.payouts", to: "vault.s_pay" },
    { from: "vault.h_claim", to: "vault.l_cp" },
    { from: "vault.h_policy", to: "vault.l_cp" },
    { from: "vault.h_claim", to: "vault.l_ca" },
    { from: "vault.h_adj", to: "vault.l_ca" },
    { from: "vault.s_cstate", to: "mart.fct_claim" },
    { from: "vault.l_cp", to: "mart.fct_claim" },
    { from: "vault.l_ca", to: "mart.fct_claim" },
    { from: "vault.s_pay", to: "mart.fct_pay" },
    { from: "vault.s_reserve", to: "mart.fct_tri" },
    { from: "vault.s_pol", to: "mart.dim_pol" },
    { from: "vault.s_phold", to: "mart.dim_pol" },
    { from: "vault.h_adj", to: "mart.dim_adj" },
    { from: "mart.fct_claim", to: "kpi.cycle" },
    { from: "mart.fct_claim", to: "kpi.leak" },
    { from: "mart.fct_claim", to: "kpi.sev" },
    { from: "mart.fct_claim", to: "kpi.freq" },
    { from: "mart.fct_pay", to: "kpi.lae" },
    { from: "mart.fct_tri", to: "kpi.lae" },
  ],
};

// ---------------------------------------------------------------------------
// merchandising
// ---------------------------------------------------------------------------

const merchandising: LineageGraph = {
  title: "Merchandising",
  vertical: "Retail",
  oneLiner:
    "Plan, buy, allocate, price, and clear assortments — sales, inventory, markdowns, and supplier performance across stores and channels.",
  nodes: [
    { id: "src.rms", label: "Oracle RMS", sub: "MMS", layer: 0, row: 0, kind: "source" },
    { id: "src.sap", label: "SAP IS-Retail", sub: "ERP", layer: 0, row: 1, kind: "source" },
    { id: "src.mhn", label: "Manhattan Active Omni", sub: "OMS", layer: 0, row: 2, kind: "source" },
    { id: "src.by", label: "Blue Yonder Planning", sub: "Planning", layer: 0, row: 3, kind: "source" },
    { id: "src.pos", label: "Toshiba TCx", sub: "Store POS", layer: 0, row: 4, kind: "source" },
    { id: "stg.sku", label: "stg_sku", sub: "view", layer: 1, row: 0, kind: "stage" },
    { id: "stg.inv", label: "stg_inventory", sub: "view", layer: 1, row: 1, kind: "stage" },
    { id: "stg.sales", label: "stg_sales_lines", sub: "view", layer: 1, row: 2, kind: "stage" },
    { id: "stg.po", label: "stg_purchase_orders", sub: "view", layer: 1, row: 3, kind: "stage" },
    { id: "stg.store", label: "stg_stores", sub: "view", layer: 1, row: 4, kind: "stage" },
    { id: "vault.h_sku", label: "hub_sku", sub: "Vault hub", layer: 2, row: 0, kind: "vault" },
    { id: "vault.h_store", label: "hub_store", sub: "Vault hub", layer: 2, row: 1, kind: "vault" },
    { id: "vault.h_supp", label: "hub_supplier", sub: "Vault hub", layer: 2, row: 2, kind: "vault" },
    { id: "vault.l_sales", label: "link_sales_line", sub: "Vault link", layer: 2, row: 3, kind: "vault" },
    { id: "vault.l_inv", label: "link_inventory_position", sub: "Vault link", layer: 2, row: 4, kind: "vault" },
    { id: "vault.s_sku", label: "sat_sku_descriptive", sub: "Vault sat", layer: 3, row: 0, kind: "vault" },
    { id: "vault.s_price", label: "sat_sku_pricing", sub: "Vault sat", layer: 3, row: 1, kind: "vault" },
    { id: "vault.s_store", label: "sat_store_descriptive", sub: "Vault sat", layer: 3, row: 2, kind: "vault" },
    { id: "vault.s_inv", label: "sat_inventory_position", sub: "Vault sat", layer: 3, row: 3, kind: "vault" },
    { id: "vault.s_sales", label: "sat_sales_line_state", sub: "Vault sat", layer: 3, row: 4, kind: "vault" },
    { id: "mart.fct_sales", label: "fact_sales_daily", sub: "fact (daily)", layer: 4, row: 0, kind: "mart" },
    { id: "mart.fct_inv", label: "fact_inventory_snapshot", sub: "fact (snap)", layer: 4, row: 1, kind: "mart" },
    { id: "mart.fct_md", label: "fact_markdown", sub: "fact (table)", layer: 4, row: 2, kind: "mart" },
    { id: "mart.dim_sku", label: "dim_sku", sub: "dim (SCD2)", layer: 4, row: 3, kind: "mart" },
    { id: "mart.dim_store", label: "dim_store", sub: "dim (table)", layer: 4, row: 4, kind: "mart" },
    { id: "kpi.st", label: "Sell-through %", sub: "mer.kpi.sell_through", layer: 5, row: 0, kind: "kpi" },
    { id: "kpi.gmroi", label: "GMROI", sub: "mer.kpi.gmroi", layer: 5, row: 1, kind: "kpi" },
    { id: "kpi.md", label: "Markdown %", sub: "mer.kpi.markdown_pct", layer: 5, row: 2, kind: "kpi" },
    { id: "kpi.turn", label: "Inventory Turn", sub: "mer.kpi.inventory_turn", layer: 5, row: 3, kind: "kpi" },
    { id: "kpi.oos", label: "Out-of-Stock Rate", sub: "mer.kpi.oos", layer: 5, row: 4, kind: "kpi" },
  ],
  edges: [
    { from: "src.rms", to: "stg.sku" },
    { from: "src.sap", to: "stg.sku" },
    { from: "src.rms", to: "stg.inv" },
    { from: "src.mhn", to: "stg.inv" },
    { from: "src.pos", to: "stg.sales" },
    { from: "src.mhn", to: "stg.sales" },
    { from: "src.sap", to: "stg.po" },
    { from: "src.by", to: "stg.po" },
    { from: "src.rms", to: "stg.store" },
    { from: "stg.sku", to: "vault.h_sku" },
    { from: "stg.sku", to: "vault.s_sku" },
    { from: "stg.sku", to: "vault.s_price" },
    { from: "stg.store", to: "vault.h_store" },
    { from: "stg.store", to: "vault.s_store" },
    { from: "stg.po", to: "vault.h_supp" },
    { from: "stg.inv", to: "vault.l_inv" },
    { from: "stg.inv", to: "vault.s_inv" },
    { from: "stg.sales", to: "vault.l_sales" },
    { from: "stg.sales", to: "vault.s_sales" },
    { from: "vault.h_sku", to: "vault.l_inv" },
    { from: "vault.h_store", to: "vault.l_inv" },
    { from: "vault.h_sku", to: "vault.l_sales" },
    { from: "vault.h_store", to: "vault.l_sales" },
    { from: "vault.l_sales", to: "mart.fct_sales" },
    { from: "vault.s_sales", to: "mart.fct_sales" },
    { from: "vault.l_inv", to: "mart.fct_inv" },
    { from: "vault.s_inv", to: "mart.fct_inv" },
    { from: "vault.s_price", to: "mart.fct_md" },
    { from: "vault.s_sku", to: "mart.dim_sku" },
    { from: "vault.s_store", to: "mart.dim_store" },
    { from: "mart.fct_sales", to: "kpi.st" },
    { from: "mart.fct_sales", to: "kpi.gmroi" },
    { from: "mart.fct_md", to: "kpi.md" },
    { from: "mart.fct_inv", to: "kpi.turn" },
    { from: "mart.fct_inv", to: "kpi.oos" },
  ],
};

// ---------------------------------------------------------------------------
// demand_planning
// ---------------------------------------------------------------------------

const demandPlanning: LineageGraph = {
  title: "Demand Planning",
  vertical: "CPG",
  oneLiner:
    "Statistical and consensus forecasts with safety-stock and OTIF checks — driving production, replenishment, and S&OP decisions.",
  nodes: [
    { id: "src.ibp", label: "SAP IBP", sub: "Demand Planning", layer: 0, row: 0, kind: "source" },
    { id: "src.kx", label: "Kinaxis RapidResponse", sub: "Concurrent Planning", layer: 0, row: 1, kind: "source" },
    { id: "src.o9", label: "o9 Digital Brain", sub: "Planning", layer: 0, row: 2, kind: "source" },
    { id: "src.ana", label: "Anaplan", sub: "Planning", layer: 0, row: 3, kind: "source" },
    { id: "src.s4", label: "SAP S/4HANA", sub: "ERP / Orders", layer: 0, row: 4, kind: "source" },
    { id: "stg.fc", label: "stg_forecasts", sub: "view", layer: 1, row: 0, kind: "stage" },
    { id: "stg.ord", label: "stg_orders", sub: "view", layer: 1, row: 1, kind: "stage" },
    { id: "stg.invp", label: "stg_inventory", sub: "view", layer: 1, row: 2, kind: "stage" },
    { id: "stg.promo", label: "stg_promotions", sub: "view", layer: 1, row: 3, kind: "stage" },
    { id: "stg.ss", label: "stg_safety_stock", sub: "view", layer: 1, row: 4, kind: "stage" },
    { id: "vault.h_prod", label: "hub_product", sub: "Vault hub", layer: 2, row: 0, kind: "vault" },
    { id: "vault.h_loc", label: "hub_location", sub: "Vault hub", layer: 2, row: 1, kind: "vault" },
    { id: "vault.h_fc", label: "hub_forecast_cycle", sub: "Vault hub", layer: 2, row: 2, kind: "vault" },
    { id: "vault.l_fp", label: "link_forecast_point", sub: "Vault link", layer: 2, row: 3, kind: "vault" },
    { id: "vault.l_ol", label: "link_order_line", sub: "Vault link", layer: 2, row: 4, kind: "vault" },
    { id: "vault.s_fp", label: "sat_forecast_point_value", sub: "Vault sat", layer: 3, row: 0, kind: "vault" },
    { id: "vault.s_ol", label: "sat_order_line_state", sub: "Vault sat", layer: 3, row: 1, kind: "vault" },
    { id: "vault.s_ss", label: "sat_safety_stock_value", sub: "Vault sat", layer: 3, row: 2, kind: "vault" },
    { id: "vault.s_prod", label: "sat_product_descriptive", sub: "Vault sat", layer: 3, row: 3, kind: "vault" },
    { id: "vault.s_cust", label: "sat_customer_descriptive", sub: "Vault sat", layer: 3, row: 4, kind: "vault" },
    { id: "mart.fct_fva", label: "fact_forecast_vs_actual", sub: "fact (table)", layer: 4, row: 0, kind: "mart" },
    { id: "mart.fct_ord", label: "fact_orders_daily", sub: "fact (daily)", layer: 4, row: 1, kind: "mart" },
    { id: "mart.fct_inv", label: "fact_inventory_position", sub: "fact (snap)", layer: 4, row: 2, kind: "mart" },
    { id: "mart.fct_pl", label: "fact_promo_lift", sub: "fact (table)", layer: 4, row: 3, kind: "mart" },
    { id: "mart.dim_prod", label: "dim_product", sub: "dim (SCD2)", layer: 4, row: 4, kind: "mart" },
    { id: "kpi.mape", label: "Forecast Accuracy (MAPE)", sub: "dem.kpi.mape", layer: 5, row: 0, kind: "kpi" },
    { id: "kpi.bias", label: "Forecast Bias", sub: "dem.kpi.bias", layer: 5, row: 1, kind: "kpi" },
    { id: "kpi.fr", label: "Fill Rate", sub: "dem.kpi.fill_rate", layer: 5, row: 2, kind: "kpi" },
    { id: "kpi.otif", label: "OTIF", sub: "dem.kpi.otif", layer: 5, row: 3, kind: "kpi" },
    { id: "kpi.id", label: "Inventory Days", sub: "dem.kpi.inventory_days", layer: 5, row: 4, kind: "kpi" },
  ],
  edges: [
    { from: "src.ibp", to: "stg.fc" },
    { from: "src.kx", to: "stg.fc" },
    { from: "src.o9", to: "stg.fc" },
    { from: "src.ana", to: "stg.fc" },
    { from: "src.s4", to: "stg.ord" },
    { from: "src.s4", to: "stg.invp" },
    { from: "src.kx", to: "stg.invp" },
    { from: "src.ibp", to: "stg.promo" },
    { from: "src.ibp", to: "stg.ss" },
    { from: "stg.fc", to: "vault.h_prod" },
    { from: "stg.fc", to: "vault.h_fc" },
    { from: "stg.fc", to: "vault.l_fp" },
    { from: "stg.fc", to: "vault.s_fp" },
    { from: "stg.ord", to: "vault.l_ol" },
    { from: "stg.ord", to: "vault.s_ol" },
    { from: "stg.ss", to: "vault.s_ss" },
    { from: "stg.invp", to: "vault.h_loc" },
    { from: "stg.invp", to: "vault.s_prod" },
    { from: "stg.ord", to: "vault.s_cust" },
    { from: "vault.h_prod", to: "vault.l_fp" },
    { from: "vault.h_loc", to: "vault.l_fp" },
    { from: "vault.h_fc", to: "vault.l_fp" },
    { from: "vault.h_prod", to: "vault.l_ol" },
    { from: "vault.l_fp", to: "mart.fct_fva" },
    { from: "vault.s_fp", to: "mart.fct_fva" },
    { from: "vault.s_ol", to: "mart.fct_ord" },
    { from: "vault.l_ol", to: "mart.fct_ord" },
    { from: "vault.s_ss", to: "mart.fct_inv" },
    { from: "vault.s_fp", to: "mart.fct_pl" },
    { from: "vault.s_prod", to: "mart.dim_prod" },
    { from: "mart.fct_fva", to: "kpi.mape" },
    { from: "mart.fct_fva", to: "kpi.bias" },
    { from: "mart.fct_ord", to: "kpi.fr" },
    { from: "mart.fct_ord", to: "kpi.otif" },
    { from: "mart.fct_inv", to: "kpi.id" },
  ],
};

// ---------------------------------------------------------------------------
// hotel_revenue_management
// ---------------------------------------------------------------------------

const hotelRevenueManagement: LineageGraph = {
  title: "Hotel Revenue Management",
  vertical: "Travel & Hospitality",
  oneLiner:
    "Dynamic pricing for room nights — BAR ladders, demand forecasts, channel mix, and compset benchmarks driving RevPAR, ADR, and occupancy.",
  nodes: [
    { id: "src.opera", label: "Oracle Opera PMS", sub: "PMS", layer: 0, row: 0, kind: "source" },
    { id: "src.amad", label: "Amadeus HotSOS / RMS", sub: "GDS/RMS", layer: 0, row: 1, kind: "source" },
    { id: "src.ideas", label: "IDeaS G3 RMS", sub: "RMS", layer: 0, row: 2, kind: "source" },
    { id: "src.duetto", label: "Duetto GameChanger", sub: "RMS", layer: 0, row: 3, kind: "source" },
    { id: "src.str", label: "STR", sub: "Compset Benchmarks", layer: 0, row: 4, kind: "source" },
    { id: "stg.res", label: "stg_reservations", sub: "view", layer: 1, row: 0, kind: "stage" },
    { id: "stg.rn", label: "stg_room_nights", sub: "view", layer: 1, row: 1, kind: "stage" },
    { id: "stg.rate", label: "stg_rate_plans", sub: "view", layer: 1, row: 2, kind: "stage" },
    { id: "stg.compset", label: "stg_compset", sub: "view", layer: 1, row: 3, kind: "stage" },
    { id: "stg.bar", label: "stg_bar_history", sub: "view", layer: 1, row: 4, kind: "stage" },
    { id: "vault.h_prop", label: "hub_property", sub: "Vault hub", layer: 2, row: 0, kind: "vault" },
    { id: "vault.h_res", label: "hub_reservation", sub: "Vault hub", layer: 2, row: 1, kind: "vault" },
    { id: "vault.h_rate", label: "hub_rate_plan", sub: "Vault hub", layer: 2, row: 2, kind: "vault" },
    { id: "vault.l_rn", label: "link_room_night", sub: "Vault link", layer: 2, row: 3, kind: "vault" },
    { id: "vault.l_bar", label: "link_bar_rate", sub: "Vault link", layer: 2, row: 4, kind: "vault" },
    { id: "vault.s_res", label: "sat_reservation_state", sub: "Vault sat", layer: 3, row: 0, kind: "vault" },
    { id: "vault.s_prop", label: "sat_property_descriptive", sub: "Vault sat", layer: 3, row: 1, kind: "vault" },
    { id: "vault.s_rate", label: "sat_rate_plan_descriptive", sub: "Vault sat", layer: 3, row: 2, kind: "vault" },
    { id: "vault.s_rn", label: "sat_room_night_state", sub: "Vault sat", layer: 3, row: 3, kind: "vault" },
    { id: "vault.s_bar", label: "sat_bar_rate", sub: "Vault sat", layer: 3, row: 4, kind: "vault" },
    { id: "mart.fct_rn", label: "fact_room_night", sub: "fact (table)", layer: 4, row: 0, kind: "mart" },
    { id: "mart.fct_bc", label: "fact_booking_curve", sub: "fact (table)", layer: 4, row: 1, kind: "mart" },
    { id: "mart.fct_cs", label: "fact_compset", sub: "fact (table)", layer: 4, row: 2, kind: "mart" },
    { id: "mart.fct_bar", label: "fact_bar_history", sub: "fact (table)", layer: 4, row: 3, kind: "mart" },
    { id: "mart.dim_prop", label: "dim_property", sub: "dim (table)", layer: 4, row: 4, kind: "mart" },
    { id: "kpi.revpar", label: "RevPAR", sub: "hrm.kpi.revpar", layer: 5, row: 0, kind: "kpi" },
    { id: "kpi.adr", label: "ADR", sub: "hrm.kpi.adr", layer: 5, row: 1, kind: "kpi" },
    { id: "kpi.occ", label: "Occupancy", sub: "hrm.kpi.occupancy", layer: 5, row: 2, kind: "kpi" },
    { id: "kpi.mpi", label: "MPI", sub: "hrm.kpi.mpi", layer: 5, row: 3, kind: "kpi" },
    { id: "kpi.rgi", label: "RGI", sub: "hrm.kpi.rgi", layer: 5, row: 4, kind: "kpi" },
  ],
  edges: [
    { from: "src.opera", to: "stg.res" },
    { from: "src.opera", to: "stg.rn" },
    { from: "src.amad", to: "stg.res" },
    { from: "src.ideas", to: "stg.rate" },
    { from: "src.duetto", to: "stg.bar" },
    { from: "src.ideas", to: "stg.bar" },
    { from: "src.str", to: "stg.compset" },
    { from: "stg.res", to: "vault.h_res" },
    { from: "stg.res", to: "vault.s_res" },
    { from: "stg.rn", to: "vault.l_rn" },
    { from: "stg.rn", to: "vault.s_rn" },
    { from: "stg.rate", to: "vault.h_rate" },
    { from: "stg.rate", to: "vault.s_rate" },
    { from: "stg.rate", to: "vault.h_prop" },
    { from: "stg.bar", to: "vault.l_bar" },
    { from: "stg.bar", to: "vault.s_bar" },
    { from: "stg.compset", to: "vault.s_prop" },
    { from: "vault.h_res", to: "vault.l_rn" },
    { from: "vault.h_prop", to: "vault.l_rn" },
    { from: "vault.h_rate", to: "vault.l_bar" },
    { from: "vault.h_prop", to: "vault.l_bar" },
    { from: "vault.l_rn", to: "mart.fct_rn" },
    { from: "vault.s_rn", to: "mart.fct_rn" },
    { from: "vault.s_res", to: "mart.fct_bc" },
    { from: "vault.s_bar", to: "mart.fct_bar" },
    { from: "vault.l_bar", to: "mart.fct_bar" },
    { from: "vault.s_prop", to: "mart.dim_prop" },
    { from: "vault.s_prop", to: "mart.fct_cs" },
    { from: "mart.fct_rn", to: "kpi.revpar" },
    { from: "mart.fct_rn", to: "kpi.adr" },
    { from: "mart.fct_rn", to: "kpi.occ" },
    { from: "mart.fct_cs", to: "kpi.mpi" },
    { from: "mart.fct_cs", to: "kpi.rgi" },
  ],
};

// ---------------------------------------------------------------------------
// mes_quality
// ---------------------------------------------------------------------------

const mesQuality: LineageGraph = {
  title: "MES & Quality",
  vertical: "Manufacturing",
  oneLiner:
    "Shop-floor execution and quality — work orders, downtime, sensor reads, scrap, and non-conformance feeding OEE and reliability.",
  nodes: [
    { id: "src.siemens", label: "Siemens Opcenter", sub: "MES", layer: 0, row: 0, kind: "source" },
    { id: "src.rock", label: "Rockwell FactoryTalk PC", sub: "MES", layer: 0, row: 1, kind: "source" },
    { id: "src.ge", label: "GE Proficy Plant Apps", sub: "MES", layer: 0, row: 2, kind: "source" },
    { id: "src.sapdm", label: "SAP Digital Manufacturing", sub: "MES", layer: 0, row: 3, kind: "source" },
    { id: "src.pi", label: "AVEVA PI System", sub: "Historian", layer: 0, row: 4, kind: "source" },
    { id: "stg.wo", label: "stg_work_orders", sub: "view", layer: 1, row: 0, kind: "stage" },
    { id: "stg.sens", label: "stg_sensor_readings", sub: "view", layer: 1, row: 1, kind: "stage" },
    { id: "stg.dt", label: "stg_downtime_events", sub: "view", layer: 1, row: 2, kind: "stage" },
    { id: "stg.qc", label: "stg_quality_checks", sub: "view", layer: 1, row: 3, kind: "stage" },
    { id: "stg.nc", label: "stg_nonconformance", sub: "view", layer: 1, row: 4, kind: "stage" },
    { id: "vault.h_wo", label: "hub_work_order", sub: "Vault hub", layer: 2, row: 0, kind: "vault" },
    { id: "vault.h_eq", label: "hub_equipment", sub: "Vault hub", layer: 2, row: 1, kind: "vault" },
    { id: "vault.h_line", label: "hub_line", sub: "Vault hub", layer: 2, row: 2, kind: "vault" },
    { id: "vault.l_el", label: "link_equipment_line", sub: "Vault link", layer: 2, row: 3, kind: "vault" },
    { id: "vault.l_nc", label: "link_nc", sub: "Vault link", layer: 2, row: 4, kind: "vault" },
    { id: "vault.s_wo", label: "sat_wo_state", sub: "Vault sat", layer: 3, row: 0, kind: "vault" },
    { id: "vault.s_eq", label: "sat_equipment_descriptive", sub: "Vault sat", layer: 3, row: 1, kind: "vault" },
    { id: "vault.s_sens", label: "sat_sensor_reading", sub: "Vault sat", layer: 3, row: 2, kind: "vault" },
    { id: "vault.s_dt", label: "sat_downtime_event", sub: "Vault sat", layer: 3, row: 3, kind: "vault" },
    { id: "vault.s_nc", label: "sat_nc_descriptive", sub: "Vault sat", layer: 3, row: 4, kind: "vault" },
    { id: "mart.fct_oee", label: "fact_oee_hourly", sub: "fact (hourly)", layer: 4, row: 0, kind: "mart" },
    { id: "mart.fct_qc", label: "fact_quality_check", sub: "fact (table)", layer: 4, row: 1, kind: "mart" },
    { id: "mart.fct_dt", label: "fact_downtime", sub: "fact (table)", layer: 4, row: 2, kind: "mart" },
    { id: "mart.fct_rel", label: "fact_equipment_reliability", sub: "fact (table)", layer: 4, row: 3, kind: "mart" },
    { id: "mart.dim_eq", label: "dim_equipment", sub: "dim (table)", layer: 4, row: 4, kind: "mart" },
    { id: "kpi.oee", label: "OEE", sub: "mes.kpi.oee", layer: 5, row: 0, kind: "kpi" },
    { id: "kpi.fpy", label: "First Pass Yield", sub: "mes.kpi.fpy", layer: 5, row: 1, kind: "kpi" },
    { id: "kpi.scrap", label: "Scrap Rate", sub: "mes.kpi.scrap", layer: 5, row: 2, kind: "kpi" },
    { id: "kpi.mtbf", label: "MTBF", sub: "mes.kpi.mtbf", layer: 5, row: 3, kind: "kpi" },
    { id: "kpi.mttr", label: "MTTR", sub: "mes.kpi.mttr", layer: 5, row: 4, kind: "kpi" },
  ],
  edges: [
    { from: "src.siemens", to: "stg.wo" },
    { from: "src.rock", to: "stg.wo" },
    { from: "src.sapdm", to: "stg.wo" },
    { from: "src.pi", to: "stg.sens" },
    { from: "src.ge", to: "stg.sens" },
    { from: "src.rock", to: "stg.dt" },
    { from: "src.siemens", to: "stg.dt" },
    { from: "src.ge", to: "stg.qc" },
    { from: "src.siemens", to: "stg.nc" },
    { from: "stg.wo", to: "vault.h_wo" },
    { from: "stg.wo", to: "vault.s_wo" },
    { from: "stg.sens", to: "vault.h_eq" },
    { from: "stg.sens", to: "vault.s_sens" },
    { from: "stg.sens", to: "vault.s_eq" },
    { from: "stg.dt", to: "vault.s_dt" },
    { from: "stg.dt", to: "vault.h_line" },
    { from: "stg.nc", to: "vault.l_nc" },
    { from: "stg.nc", to: "vault.s_nc" },
    { from: "vault.h_eq", to: "vault.l_el" },
    { from: "vault.h_line", to: "vault.l_el" },
    { from: "vault.h_wo", to: "vault.l_nc" },
    { from: "vault.l_el", to: "mart.fct_oee" },
    { from: "vault.s_sens", to: "mart.fct_oee" },
    { from: "vault.s_wo", to: "mart.fct_qc" },
    { from: "vault.l_nc", to: "mart.fct_qc" },
    { from: "vault.s_dt", to: "mart.fct_dt" },
    { from: "vault.s_eq", to: "mart.fct_rel" },
    { from: "vault.s_eq", to: "mart.dim_eq" },
    { from: "mart.fct_oee", to: "kpi.oee" },
    { from: "mart.fct_qc", to: "kpi.fpy" },
    { from: "mart.fct_qc", to: "kpi.scrap" },
    { from: "mart.fct_rel", to: "kpi.mtbf" },
    { from: "mart.fct_dt", to: "kpi.mttr" },
  ],
};

// ---------------------------------------------------------------------------
// pharmacovigilance
// ---------------------------------------------------------------------------

const pharmacovigilance: LineageGraph = {
  title: "Pharmacovigilance",
  vertical: "Life Sciences",
  oneLiner:
    "ICSR intake, MedDRA coding, regulatory submission, and signal detection — drug safety operations end-to-end.",
  nodes: [
    { id: "src.argus", label: "Oracle Argus Safety", sub: "Safety Database", layer: 0, row: 0, kind: "source" },
    { id: "src.aris", label: "ArisGlobal LifeSphere", sub: "Safety Database", layer: 0, row: 1, kind: "source" },
    { id: "src.veeva", label: "Veeva Vault Safety", sub: "Safety Database", layer: 0, row: 2, kind: "source" },
    { id: "src.faers", label: "FDA FAERS", sub: "Public AE Feed", layer: 0, row: 3, kind: "source" },
    { id: "src.meddra", label: "MedDRA", sub: "Terminology", layer: 0, row: 4, kind: "source" },
    { id: "stg.icsr", label: "stg_icsrs", sub: "view", layer: 1, row: 0, kind: "stage" },
    { id: "stg.ae", label: "stg_ae_terms", sub: "view", layer: 1, row: 1, kind: "stage" },
    { id: "stg.sub", label: "stg_submissions", sub: "view", layer: 1, row: 2, kind: "stage" },
    { id: "stg.sig", label: "stg_signals", sub: "view", layer: 1, row: 3, kind: "stage" },
    { id: "stg.prod", label: "stg_products", sub: "view", layer: 1, row: 4, kind: "stage" },
    { id: "vault.h_icsr", label: "hub_icsr", sub: "Vault hub", layer: 2, row: 0, kind: "vault" },
    { id: "vault.h_prod", label: "hub_product", sub: "Vault hub", layer: 2, row: 1, kind: "vault" },
    { id: "vault.h_md", label: "hub_meddra_term", sub: "Vault hub", layer: 2, row: 2, kind: "vault" },
    { id: "vault.l_ae", label: "link_ae_meddra", sub: "Vault link", layer: 2, row: 3, kind: "vault" },
    { id: "vault.l_sub", label: "link_submission", sub: "Vault link", layer: 2, row: 4, kind: "vault" },
    { id: "vault.s_icsr", label: "sat_icsr_state", sub: "Vault sat", layer: 3, row: 0, kind: "vault" },
    { id: "vault.s_prod", label: "sat_product_descriptive", sub: "Vault sat", layer: 3, row: 1, kind: "vault" },
    { id: "vault.s_md", label: "sat_meddra_descriptive", sub: "Vault sat", layer: 3, row: 2, kind: "vault" },
    { id: "vault.s_sub", label: "sat_submission_state", sub: "Vault sat", layer: 3, row: 3, kind: "vault" },
    { id: "vault.s_sig", label: "sat_signal_state", sub: "Vault sat", layer: 3, row: 4, kind: "vault" },
    { id: "mart.fct_icsr", label: "fact_icsr", sub: "fact (table)", layer: 4, row: 0, kind: "mart" },
    { id: "mart.fct_sub", label: "fact_submission", sub: "fact (table)", layer: 4, row: 1, kind: "mart" },
    { id: "mart.fct_sig", label: "fact_signal", sub: "fact (table)", layer: 4, row: 2, kind: "mart" },
    { id: "mart.fct_vol", label: "fact_case_volume_daily", sub: "fact (daily)", layer: 4, row: 3, kind: "mart" },
    { id: "mart.dim_md", label: "dim_meddra", sub: "dim (SCD2)", layer: 4, row: 4, kind: "mart" },
    { id: "kpi.cpt", label: "Case Processing Time", sub: "pv.kpi.case_processing_time", layer: 5, row: 0, kind: "kpi" },
    { id: "kpi.sl", label: "Signal Detection Latency", sub: "pv.kpi.signal_latency", layer: 5, row: 1, kind: "kpi" },
    { id: "kpi.st", label: "Submission Timeliness", sub: "pv.kpi.submission_timeliness", layer: 5, row: 2, kind: "kpi" },
    { id: "kpi.vol", label: "ICSR Volume", sub: "pv.kpi.icsr_volume", layer: 5, row: 3, kind: "kpi" },
    { id: "kpi.acc", label: "AE→PT Mapping Accuracy", sub: "pv.kpi.ae_pt_accuracy", layer: 5, row: 4, kind: "kpi" },
  ],
  edges: [
    { from: "src.argus", to: "stg.icsr" },
    { from: "src.aris", to: "stg.icsr" },
    { from: "src.veeva", to: "stg.icsr" },
    { from: "src.faers", to: "stg.icsr" },
    { from: "src.meddra", to: "stg.ae" },
    { from: "src.argus", to: "stg.ae" },
    { from: "src.argus", to: "stg.sub" },
    { from: "src.veeva", to: "stg.sub" },
    { from: "src.aris", to: "stg.sig" },
    { from: "src.argus", to: "stg.prod" },
    { from: "stg.icsr", to: "vault.h_icsr" },
    { from: "stg.icsr", to: "vault.s_icsr" },
    { from: "stg.prod", to: "vault.h_prod" },
    { from: "stg.prod", to: "vault.s_prod" },
    { from: "stg.ae", to: "vault.h_md" },
    { from: "stg.ae", to: "vault.s_md" },
    { from: "stg.ae", to: "vault.l_ae" },
    { from: "stg.sub", to: "vault.l_sub" },
    { from: "stg.sub", to: "vault.s_sub" },
    { from: "stg.sig", to: "vault.s_sig" },
    { from: "vault.h_icsr", to: "vault.l_ae" },
    { from: "vault.h_md", to: "vault.l_ae" },
    { from: "vault.h_icsr", to: "vault.l_sub" },
    { from: "vault.s_icsr", to: "mart.fct_icsr" },
    { from: "vault.l_ae", to: "mart.fct_icsr" },
    { from: "vault.l_sub", to: "mart.fct_sub" },
    { from: "vault.s_sub", to: "mart.fct_sub" },
    { from: "vault.s_sig", to: "mart.fct_sig" },
    { from: "vault.s_icsr", to: "mart.fct_vol" },
    { from: "vault.s_md", to: "mart.dim_md" },
    { from: "mart.fct_icsr", to: "kpi.cpt" },
    { from: "mart.fct_sig", to: "kpi.sl" },
    { from: "mart.fct_sub", to: "kpi.st" },
    { from: "mart.fct_vol", to: "kpi.vol" },
    { from: "mart.fct_icsr", to: "kpi.acc" },
  ],
};

// ---------------------------------------------------------------------------
// ehr_integrations  (FHIR R4 / HL7 v2 / USCDI)
// ---------------------------------------------------------------------------

const ehrIntegrations: LineageGraph = {
  title: "EHR Integrations",
  vertical: "Healthcare",
  oneLiner:
    "Bidirectional clinical data flow — Epic/Cerner FHIR + HL7 v2 ADT/ORU into a longitudinal patient record feeding analytics, payer, and engagement systems.",
  nodes: [
    // sources
    { id: "src.epic", label: "Epic", sub: "EHR (EpicCare)", layer: 0, row: 0, kind: "source" },
    { id: "src.cerner", label: "Cerner Millennium", sub: "EHR", layer: 0, row: 1, kind: "source" },
    { id: "src.athena", label: "athenahealth", sub: "EHR (athenaClinicals)", layer: 0, row: 2, kind: "source" },
    { id: "src.allscripts", label: "Allscripts Sunrise", sub: "EHR", layer: 0, row: 3, kind: "source" },
    { id: "src.redox", label: "Redox / Mirth", sub: "Integration Engine", layer: 0, row: 4, kind: "source" },
    // staging
    { id: "stg.patient", label: "stg_patient", sub: "FHIR Patient", layer: 1, row: 0, kind: "stage" },
    { id: "stg.encounter", label: "stg_encounter", sub: "FHIR Encounter", layer: 1, row: 1, kind: "stage" },
    { id: "stg.observation", label: "stg_observation", sub: "FHIR Observation (LOINC)", layer: 1, row: 2, kind: "stage" },
    { id: "stg.medreq", label: "stg_medication_request", sub: "FHIR MedicationRequest", layer: 1, row: 3, kind: "stage" },
    { id: "stg.hl7v2", label: "stg_hl7v2_message", sub: "ADT/ORM/ORU", layer: 1, row: 4, kind: "stage" },
    // vault hubs/links
    { id: "vault.h_patient", label: "hub_patient", sub: "Vault hub", layer: 2, row: 0, kind: "vault" },
    { id: "vault.h_practitioner", label: "hub_practitioner", sub: "Vault hub", layer: 2, row: 1, kind: "vault" },
    { id: "vault.h_org", label: "hub_organization", sub: "Vault hub", layer: 2, row: 2, kind: "vault" },
    { id: "vault.l_enc_pat", label: "link_encounter_patient", sub: "Vault link", layer: 2, row: 3, kind: "vault" },
    { id: "vault.l_obs_enc", label: "link_observation_encounter", sub: "Vault link", layer: 2, row: 4, kind: "vault" },
    // vault sats
    { id: "vault.s_patient", label: "sat_patient_demographics", sub: "Vault sat (bitemporal)", layer: 3, row: 0, kind: "vault" },
    { id: "vault.s_encounter", label: "sat_encounter_state", sub: "Vault sat", layer: 3, row: 1, kind: "vault" },
    { id: "vault.s_obs", label: "sat_observation_value", sub: "Vault sat", layer: 3, row: 2, kind: "vault" },
    { id: "vault.s_medreq", label: "sat_medication_request", sub: "Vault sat", layer: 3, row: 3, kind: "vault" },
    { id: "vault.s_smart", label: "sat_smart_authorization", sub: "Vault sat", layer: 3, row: 4, kind: "vault" },
    // marts
    { id: "mart.fct_enc", label: "fact_encounter", sub: "fact (per encounter)", layer: 4, row: 0, kind: "mart" },
    { id: "mart.fct_hl7", label: "fact_hl7_message", sub: "fact (per message)", layer: 4, row: 1, kind: "mart" },
    { id: "mart.fct_fhir", label: "fact_fhir_request", sub: "fact (per API call)", layer: 4, row: 2, kind: "mart" },
    { id: "mart.fct_match", label: "fact_match_daily", sub: "fact (daily)", layer: 4, row: 3, kind: "mart" },
    { id: "mart.dim_pat", label: "dim_patient", sub: "dim (SCD2)", layer: 4, row: 4, kind: "mart" },
    // KPIs
    { id: "kpi.msg_succ", label: "HL7 Message Success", sub: "ehr.kpi.message_success", layer: 5, row: 0, kind: "kpi" },
    { id: "kpi.fhir_lat", label: "FHIR Latency P95", sub: "ehr.kpi.fhir_latency", layer: 5, row: 1, kind: "kpi" },
    { id: "kpi.match", label: "Patient Match Rate", sub: "ehr.kpi.dq_match_rate", layer: 5, row: 2, kind: "kpi" },
    { id: "kpi.adt_lag", label: "ADT Event Lag", sub: "ehr.kpi.adt_lag", layer: 5, row: 3, kind: "kpi" },
    { id: "kpi.uscdi", label: "USCDI Completeness", sub: "ehr.kpi.uscdi_completeness", layer: 5, row: 4, kind: "kpi" },
  ],
  edges: [
    { from: "src.epic", to: "stg.patient" },
    { from: "src.cerner", to: "stg.patient" },
    { from: "src.athena", to: "stg.encounter" },
    { from: "src.epic", to: "stg.encounter" },
    { from: "src.cerner", to: "stg.observation" },
    { from: "src.allscripts", to: "stg.medreq" },
    { from: "src.redox", to: "stg.hl7v2" },
    { from: "src.epic", to: "stg.hl7v2" },
    { from: "stg.patient", to: "vault.h_patient" },
    { from: "stg.patient", to: "vault.s_patient" },
    { from: "stg.encounter", to: "vault.l_enc_pat" },
    { from: "stg.encounter", to: "vault.s_encounter" },
    { from: "stg.observation", to: "vault.l_obs_enc" },
    { from: "stg.observation", to: "vault.s_obs" },
    { from: "stg.medreq", to: "vault.s_medreq" },
    { from: "stg.medreq", to: "vault.h_practitioner" },
    { from: "stg.hl7v2", to: "vault.h_org" },
    { from: "vault.h_patient", to: "vault.l_enc_pat" },
    { from: "vault.h_patient", to: "vault.l_obs_enc" },
    { from: "vault.l_enc_pat", to: "mart.fct_enc" },
    { from: "vault.s_encounter", to: "mart.fct_enc" },
    { from: "vault.s_obs", to: "mart.fct_enc" },
    { from: "vault.s_medreq", to: "mart.fct_enc" },
    { from: "stg.hl7v2", to: "mart.fct_hl7" },
    { from: "vault.s_smart", to: "mart.fct_fhir" },
    { from: "vault.s_patient", to: "mart.fct_match" },
    { from: "vault.s_patient", to: "mart.dim_pat" },
    { from: "mart.fct_hl7", to: "kpi.msg_succ" },
    { from: "mart.fct_fhir", to: "kpi.fhir_lat" },
    { from: "mart.fct_match", to: "kpi.match" },
    { from: "mart.fct_hl7", to: "kpi.adt_lag" },
    { from: "mart.fct_enc", to: "kpi.uscdi" },
  ],
};

// ---------------------------------------------------------------------------
// capital_markets  (FIX 4.4/5.0 SP2 / FpML 5.x / ISO 20022 securities)
// ---------------------------------------------------------------------------

const capitalMarkets: LineageGraph = {
  title: "Capital Markets",
  vertical: "BFSI",
  oneLiner:
    "Front-to-back trade lifecycle — FIX order routing and execution through FpML lifecycle and ISO 20022 settlement, with TCA, breaks, and cleared share.",
  nodes: [
    { id: "src.murex", label: "Murex MX.3", sub: "Trading Platform", layer: 0, row: 0, kind: "source" },
    { id: "src.calypso", label: "Calypso", sub: "Trading Platform", layer: 0, row: 1, kind: "source" },
    { id: "src.bbg", label: "Bloomberg AIM", sub: "OMS", layer: 0, row: 2, kind: "source" },
    { id: "src.fidessa", label: "ION Fidessa", sub: "OEMS", layer: 0, row: 3, kind: "source" },
    { id: "src.dtcc", label: "DTCC CTM / MarkitSERV", sub: "Affirmation", layer: 0, row: 4, kind: "source" },
    { id: "stg.order", label: "stg_order", sub: "FIX 35=D", layer: 1, row: 0, kind: "stage" },
    { id: "stg.exec", label: "stg_execution", sub: "FIX 35=8", layer: 1, row: 1, kind: "stage" },
    { id: "stg.trade", label: "stg_trade", sub: "FpML Trade", layer: 1, row: 2, kind: "stage" },
    { id: "stg.settle", label: "stg_settlement_instruction", sub: "ISO 20022 sese.023", layer: 1, row: 3, kind: "stage" },
    { id: "stg.md", label: "stg_market_data_snapshot", sub: "L1 quotes", layer: 1, row: 4, kind: "stage" },
    { id: "vault.h_order", label: "hub_order", sub: "Vault hub", layer: 2, row: 0, kind: "vault" },
    { id: "vault.h_trade", label: "hub_trade", sub: "Vault hub (USI)", layer: 2, row: 1, kind: "vault" },
    { id: "vault.h_inst", label: "hub_instrument", sub: "Vault hub (ISIN)", layer: 2, row: 2, kind: "vault" },
    { id: "vault.h_cpty", label: "hub_counterparty", sub: "Vault hub (LEI)", layer: 2, row: 3, kind: "vault" },
    { id: "vault.l_trade", label: "link_trade_components", sub: "Vault link", layer: 2, row: 4, kind: "vault" },
    { id: "vault.s_order", label: "sat_order_state", sub: "Vault sat", layer: 3, row: 0, kind: "vault" },
    { id: "vault.s_exec", label: "sat_execution", sub: "Vault sat", layer: 3, row: 1, kind: "vault" },
    { id: "vault.s_trade", label: "sat_trade_state", sub: "Vault sat (bitemporal FpML)", layer: 3, row: 2, kind: "vault" },
    { id: "vault.s_inst", label: "sat_instrument_descriptive", sub: "Vault sat", layer: 3, row: 3, kind: "vault" },
    { id: "vault.s_cpty", label: "sat_counterparty_descriptive", sub: "Vault sat", layer: 3, row: 4, kind: "vault" },
    { id: "mart.fct_exec", label: "fact_execution", sub: "fact (per fill)", layer: 4, row: 0, kind: "mart" },
    { id: "mart.fct_trade", label: "fact_trade", sub: "fact (per trade)", layer: 4, row: 1, kind: "mart" },
    { id: "mart.fct_settle", label: "fact_settlement", sub: "fact (per SSI)", layer: 4, row: 2, kind: "mart" },
    { id: "mart.fct_pos", label: "fact_position_daily", sub: "fact (daily)", layer: 4, row: 3, kind: "mart" },
    { id: "mart.fct_break", label: "fact_trade_break", sub: "fact (per break)", layer: 4, row: 4, kind: "mart" },
    { id: "kpi.break", label: "Trade Break Rate", sub: "cm.kpi.trade_break_rate", layer: 5, row: 0, kind: "kpi" },
    { id: "kpi.t1", label: "T+1 Settlement Rate", sub: "cm.kpi.t_plus_1_settlement", layer: 5, row: 1, kind: "kpi" },
    { id: "kpi.slip", label: "Execution Slippage", sub: "cm.kpi.execution_slippage", layer: 5, row: 2, kind: "kpi" },
    { id: "kpi.affirm", label: "T+0 Affirmation Rate", sub: "cm.kpi.affirmation_rate", layer: 5, row: 3, kind: "kpi" },
    { id: "kpi.life", label: "Lifecycle Event Lag", sub: "cm.kpi.lifecycle_event_lag", layer: 5, row: 4, kind: "kpi" },
  ],
  edges: [
    { from: "src.bbg", to: "stg.order" },
    { from: "src.fidessa", to: "stg.order" },
    { from: "src.fidessa", to: "stg.exec" },
    { from: "src.murex", to: "stg.trade" },
    { from: "src.calypso", to: "stg.trade" },
    { from: "src.dtcc", to: "stg.settle" },
    { from: "src.bbg", to: "stg.md" },
    { from: "stg.order", to: "vault.h_order" },
    { from: "stg.order", to: "vault.s_order" },
    { from: "stg.exec", to: "vault.s_exec" },
    { from: "stg.trade", to: "vault.h_trade" },
    { from: "stg.trade", to: "vault.s_trade" },
    { from: "stg.trade", to: "vault.h_inst" },
    { from: "stg.trade", to: "vault.h_cpty" },
    { from: "stg.trade", to: "vault.s_inst" },
    { from: "stg.trade", to: "vault.s_cpty" },
    { from: "vault.h_trade", to: "vault.l_trade" },
    { from: "vault.h_inst", to: "vault.l_trade" },
    { from: "vault.h_cpty", to: "vault.l_trade" },
    { from: "vault.s_exec", to: "mart.fct_exec" },
    { from: "vault.l_trade", to: "mart.fct_trade" },
    { from: "vault.s_trade", to: "mart.fct_trade" },
    { from: "stg.settle", to: "mart.fct_settle" },
    { from: "vault.l_trade", to: "mart.fct_pos" },
    { from: "vault.s_trade", to: "mart.fct_break" },
    { from: "mart.fct_break", to: "kpi.break" },
    { from: "mart.fct_settle", to: "kpi.t1" },
    { from: "mart.fct_exec", to: "kpi.slip" },
    { from: "mart.fct_trade", to: "kpi.affirm" },
    { from: "mart.fct_trade", to: "kpi.life" },
  ],
};

// ---------------------------------------------------------------------------
// smart_metering  (ANSI C12.19/22, DLMS/COSEM, CIM 61968-9)
// ---------------------------------------------------------------------------

const smartMetering: LineageGraph = {
  title: "Smart Metering",
  vertical: "Energy",
  oneLiner:
    "AMI head-end + MDM — interval reads, register snapshots, events, and outage state feeding billing accuracy, NTL, and AMI uptime.",
  nodes: [
    { id: "src.itron", label: "Itron IEE", sub: "Head-end / MDM", layer: 0, row: 0, kind: "source" },
    { id: "src.lg", label: "Landis+Gyr Gridstream", sub: "Head-end", layer: 0, row: 1, kind: "source" },
    { id: "src.honeywell", label: "Honeywell Connexo", sub: "MDM", layer: 0, row: 2, kind: "source" },
    { id: "src.oracle", label: "Oracle MDM", sub: "MDM", layer: 0, row: 3, kind: "source" },
    { id: "src.fnd", label: "Cisco IoT FND", sub: "Network Mgmt", layer: 0, row: 4, kind: "source" },
    { id: "stg.read", label: "stg_meter_read", sub: "OBIS interval", layer: 1, row: 0, kind: "stage" },
    { id: "stg.register", label: "stg_register_reading", sub: "C12.19 Tbl 23/24", layer: 1, row: 1, kind: "stage" },
    { id: "stg.event", label: "stg_meter_event", sub: "C12.19 Tbl 25", layer: 1, row: 2, kind: "stage" },
    { id: "stg.outage", label: "stg_outage", sub: "CIM EndDeviceEvent", layer: 1, row: 3, kind: "stage" },
    { id: "stg.bill", label: "stg_billing_determinant", sub: "view", layer: 1, row: 4, kind: "stage" },
    { id: "vault.h_meter", label: "hub_meter", sub: "Vault hub", layer: 2, row: 0, kind: "vault" },
    { id: "vault.h_sp", label: "hub_service_point", sub: "Vault hub (UsagePoint)", layer: 2, row: 1, kind: "vault" },
    { id: "vault.h_outage", label: "hub_outage", sub: "Vault hub", layer: 2, row: 2, kind: "vault" },
    { id: "vault.l_msp", label: "link_meter_service_point", sub: "Vault link", layer: 2, row: 3, kind: "vault" },
    { id: "vault.l_outage", label: "link_outage_meter", sub: "Vault link", layer: 2, row: 4, kind: "vault" },
    { id: "vault.s_meter", label: "sat_meter_descriptive", sub: "Vault sat", layer: 3, row: 0, kind: "vault" },
    { id: "vault.s_register", label: "sat_register_reading", sub: "Vault sat", layer: 3, row: 1, kind: "vault" },
    { id: "vault.s_event", label: "sat_meter_event", sub: "Vault sat", layer: 3, row: 2, kind: "vault" },
    { id: "vault.s_outage", label: "sat_outage_state", sub: "Vault sat", layer: 3, row: 3, kind: "vault" },
    { id: "vault.s_fw", label: "sat_firmware_deployment", sub: "Vault sat", layer: 3, row: 4, kind: "vault" },
    { id: "mart.fct_int", label: "fact_interval_15m", sub: "fact (15m)", layer: 4, row: 0, kind: "mart" },
    { id: "mart.fct_reg", label: "fact_register_daily", sub: "fact (daily)", layer: 4, row: 1, kind: "mart" },
    { id: "mart.fct_evt", label: "fact_event", sub: "fact (per event)", layer: 4, row: 2, kind: "mart" },
    { id: "mart.fct_bill", label: "fact_bill", sub: "fact (per bill)", layer: 4, row: 3, kind: "mart" },
    { id: "mart.dim_meter", label: "dim_meter", sub: "dim (SCD2)", layer: 4, row: 4, kind: "mart" },
    { id: "kpi.read", label: "Read Success %", sub: "ami.kpi.read_success", layer: 5, row: 0, kind: "kpi" },
    { id: "kpi.bill", label: "Billing Accuracy", sub: "ami.kpi.billing_accuracy", layer: 5, row: 1, kind: "kpi" },
    { id: "kpi.ntl", label: "Non-Technical Loss", sub: "ami.kpi.ntl", layer: 5, row: 2, kind: "kpi" },
    { id: "kpi.uptime", label: "AMI Uptime", sub: "ami.kpi.ami_uptime", layer: 5, row: 3, kind: "kpi" },
    { id: "kpi.tamper", label: "Tamper Alarm Rate", sub: "ami.kpi.tamper_alarm_rate", layer: 5, row: 4, kind: "kpi" },
  ],
  edges: [
    { from: "src.itron", to: "stg.read" },
    { from: "src.lg", to: "stg.read" },
    { from: "src.honeywell", to: "stg.register" },
    { from: "src.oracle", to: "stg.register" },
    { from: "src.itron", to: "stg.event" },
    { from: "src.fnd", to: "stg.event" },
    { from: "src.lg", to: "stg.outage" },
    { from: "src.oracle", to: "stg.bill" },
    { from: "stg.read", to: "vault.h_meter" },
    { from: "stg.read", to: "vault.h_sp" },
    { from: "stg.read", to: "vault.l_msp" },
    { from: "stg.read", to: "vault.s_register" },
    { from: "stg.register", to: "vault.s_register" },
    { from: "stg.event", to: "vault.s_event" },
    { from: "stg.event", to: "vault.s_meter" },
    { from: "stg.outage", to: "vault.h_outage" },
    { from: "stg.outage", to: "vault.l_outage" },
    { from: "stg.outage", to: "vault.s_outage" },
    { from: "vault.h_meter", to: "vault.l_outage" },
    { from: "vault.s_register", to: "mart.fct_int" },
    { from: "vault.s_register", to: "mart.fct_reg" },
    { from: "vault.s_event", to: "mart.fct_evt" },
    { from: "stg.bill", to: "mart.fct_bill" },
    { from: "vault.s_meter", to: "mart.dim_meter" },
    { from: "vault.s_fw", to: "mart.dim_meter" },
    { from: "mart.fct_int", to: "kpi.read" },
    { from: "mart.fct_bill", to: "kpi.bill" },
    { from: "mart.fct_bill", to: "kpi.ntl" },
    { from: "mart.fct_evt", to: "kpi.uptime" },
    { from: "mart.fct_evt", to: "kpi.tamper" },
  ],
};

// ---------------------------------------------------------------------------
// clinical_trials  (CDISC SDTM/ADaM/ODM-XML)
// ---------------------------------------------------------------------------

const clinicalTrials: LineageGraph = {
  title: "Clinical Trials",
  vertical: "Life Sciences",
  oneLiner:
    "Protocol design through database lock — site activation, subject enrollment, CRF capture, and SDTM/ADaM derivation feeding enrollment, AE, and DBL KPIs.",
  nodes: [
    { id: "src.veeva", label: "Veeva Vault Clinical", sub: "eClinical Suite", layer: 0, row: 0, kind: "source" },
    { id: "src.medidata", label: "Medidata Rave EDC", sub: "EDC", layer: 0, row: 1, kind: "source" },
    { id: "src.oracle", label: "Oracle Clinical One", sub: "eClinical", layer: 0, row: 2, kind: "source" },
    { id: "src.iqvia", label: "IQVIA CTMS", sub: "CTMS", layer: 0, row: 3, kind: "source" },
    { id: "src.signant", label: "Signant SmartSignals", sub: "eCOA", layer: 0, row: 4, kind: "source" },
    { id: "stg.subject", label: "stg_subject", sub: "SDTM DM", layer: 1, row: 0, kind: "stage" },
    { id: "stg.visit", label: "stg_visit", sub: "SDTM SV", layer: 1, row: 1, kind: "stage" },
    { id: "stg.ae", label: "stg_adverse_event", sub: "SDTM AE", layer: 1, row: 2, kind: "stage" },
    { id: "stg.lab", label: "stg_lab", sub: "SDTM LB", layer: 1, row: 3, kind: "stage" },
    { id: "stg.query", label: "stg_data_query", sub: "ODM Query", layer: 1, row: 4, kind: "stage" },
    { id: "vault.h_study", label: "hub_study", sub: "Vault hub", layer: 2, row: 0, kind: "vault" },
    { id: "vault.h_site", label: "hub_site", sub: "Vault hub", layer: 2, row: 1, kind: "vault" },
    { id: "vault.h_subj", label: "hub_subject", sub: "Vault hub (USUBJID)", layer: 2, row: 2, kind: "vault" },
    { id: "vault.l_subj_site", label: "link_subject_site", sub: "Vault link", layer: 2, row: 3, kind: "vault" },
    { id: "vault.l_subj_ae", label: "link_subject_ae", sub: "Vault link", layer: 2, row: 4, kind: "vault" },
    { id: "vault.s_study", label: "sat_study_descriptive", sub: "Vault sat", layer: 3, row: 0, kind: "vault" },
    { id: "vault.s_site", label: "sat_site_state", sub: "Vault sat", layer: 3, row: 1, kind: "vault" },
    { id: "vault.s_subj", label: "sat_subject_state", sub: "Vault sat", layer: 3, row: 2, kind: "vault" },
    { id: "vault.s_ae", label: "sat_adverse_event", sub: "Vault sat (MedDRA)", layer: 3, row: 3, kind: "vault" },
    { id: "vault.s_visit", label: "sat_visit_state", sub: "Vault sat", layer: 3, row: 4, kind: "vault" },
    { id: "mart.fct_enr", label: "fact_enrollment_daily", sub: "fact (daily)", layer: 4, row: 0, kind: "mart" },
    { id: "mart.fct_visit", label: "fact_visit", sub: "fact (per visit)", layer: 4, row: 1, kind: "mart" },
    { id: "mart.fct_ae", label: "fact_adverse_event", sub: "fact (per AE)", layer: 4, row: 2, kind: "mart" },
    { id: "mart.fct_query", label: "fact_data_query", sub: "fact (per query)", layer: 4, row: 3, kind: "mart" },
    { id: "mart.fct_dbl", label: "fact_database_lock", sub: "fact (per lock)", layer: 4, row: 4, kind: "mart" },
    { id: "kpi.enr", label: "Enrollment Rate", sub: "ct.kpi.enrollment_rate", layer: 5, row: 0, kind: "kpi" },
    { id: "kpi.act", label: "Site Activation Time", sub: "ct.kpi.site_activation_time", layer: 5, row: 1, kind: "kpi" },
    { id: "kpi.sae", label: "Serious AE Rate", sub: "ct.kpi.serious_ae_rate", layer: 5, row: 2, kind: "kpi" },
    { id: "kpi.qrt", label: "Query Resolution Time", sub: "ct.kpi.query_resolution_time", layer: 5, row: 3, kind: "kpi" },
    { id: "kpi.dbl", label: "Database Lock Cycle", sub: "ct.kpi.dbl_cycle", layer: 5, row: 4, kind: "kpi" },
  ],
  edges: [
    { from: "src.veeva", to: "stg.subject" },
    { from: "src.medidata", to: "stg.subject" },
    { from: "src.medidata", to: "stg.visit" },
    { from: "src.oracle", to: "stg.visit" },
    { from: "src.medidata", to: "stg.ae" },
    { from: "src.signant", to: "stg.lab" },
    { from: "src.iqvia", to: "stg.query" },
    { from: "src.medidata", to: "stg.query" },
    { from: "stg.subject", to: "vault.h_subj" },
    { from: "stg.subject", to: "vault.s_subj" },
    { from: "stg.subject", to: "vault.l_subj_site" },
    { from: "stg.visit", to: "vault.s_visit" },
    { from: "stg.ae", to: "vault.l_subj_ae" },
    { from: "stg.ae", to: "vault.s_ae" },
    { from: "stg.lab", to: "vault.s_visit" },
    { from: "vault.h_study", to: "vault.s_study" },
    { from: "vault.h_site", to: "vault.s_site" },
    { from: "vault.h_subj", to: "vault.l_subj_site" },
    { from: "vault.h_subj", to: "vault.l_subj_ae" },
    { from: "vault.h_site", to: "vault.l_subj_site" },
    { from: "vault.s_subj", to: "mart.fct_enr" },
    { from: "vault.s_site", to: "mart.fct_enr" },
    { from: "vault.s_visit", to: "mart.fct_visit" },
    { from: "vault.s_ae", to: "mart.fct_ae" },
    { from: "stg.query", to: "mart.fct_query" },
    { from: "vault.s_study", to: "mart.fct_dbl" },
    { from: "mart.fct_enr", to: "kpi.enr" },
    { from: "mart.fct_enr", to: "kpi.act" },
    { from: "mart.fct_ae", to: "kpi.sae" },
    { from: "mart.fct_query", to: "kpi.qrt" },
    { from: "mart.fct_dbl", to: "kpi.dbl" },
  ],
};

// ---------------------------------------------------------------------------
// cloud_finops  (FinOps FOCUS 1.x)
// ---------------------------------------------------------------------------

const cloudFinops: LineageGraph = {
  title: "Cloud FinOps",
  vertical: "HiTech",
  oneLiner:
    "Multi-cloud cost visibility — AWS CUR / Azure / GCP / OCI billing exports normalised to FOCUS, with allocation, commitment use, and unit-economics KPIs.",
  nodes: [
    { id: "src.aws", label: "AWS CUR (FOCUS)", sub: "Cloud Billing", layer: 0, row: 0, kind: "source" },
    { id: "src.azure", label: "Azure Cost Mgmt", sub: "Cloud Billing", layer: 0, row: 1, kind: "source" },
    { id: "src.gcp", label: "GCP Billing Export", sub: "Cloud Billing", layer: 0, row: 2, kind: "source" },
    { id: "src.oci", label: "OCI Cost Analysis", sub: "Cloud Billing", layer: 0, row: 3, kind: "source" },
    { id: "src.opencost", label: "OpenCost / Kubecost", sub: "K8s allocation", layer: 0, row: 4, kind: "source" },
    { id: "stg.charge", label: "stg_charge_record", sub: "FOCUS charge line", layer: 1, row: 0, kind: "stage" },
    { id: "stg.tag", label: "stg_resource_tag", sub: "view", layer: 1, row: 1, kind: "stage" },
    { id: "stg.commit", label: "stg_commitment", sub: "RI/Savings/CUD", layer: 1, row: 2, kind: "stage" },
    { id: "stg.budget", label: "stg_budget", sub: "view", layer: 1, row: 3, kind: "stage" },
    { id: "stg.anom", label: "stg_anomaly", sub: "view", layer: 1, row: 4, kind: "stage" },
    { id: "vault.h_acct", label: "hub_billing_account", sub: "Vault hub", layer: 2, row: 0, kind: "vault" },
    { id: "vault.h_svc", label: "hub_service", sub: "Vault hub", layer: 2, row: 1, kind: "vault" },
    { id: "vault.h_res", label: "hub_resource", sub: "Vault hub", layer: 2, row: 2, kind: "vault" },
    { id: "vault.h_commit", label: "hub_commitment", sub: "Vault hub", layer: 2, row: 3, kind: "vault" },
    { id: "vault.l_charge", label: "link_charge_line", sub: "Vault link", layer: 2, row: 4, kind: "vault" },
    { id: "vault.s_acct", label: "sat_billing_account", sub: "Vault sat", layer: 3, row: 0, kind: "vault" },
    { id: "vault.s_res", label: "sat_resource", sub: "Vault sat", layer: 3, row: 1, kind: "vault" },
    { id: "vault.s_tag", label: "sat_resource_tags", sub: "Vault sat", layer: 3, row: 2, kind: "vault" },
    { id: "vault.s_charge", label: "sat_charge_line", sub: "Vault sat", layer: 3, row: 3, kind: "vault" },
    { id: "vault.s_commit", label: "sat_commitment", sub: "Vault sat", layer: 3, row: 4, kind: "vault" },
    { id: "mart.fct_spend", label: "fact_spend_daily", sub: "fact (daily)", layer: 4, row: 0, kind: "mart" },
    { id: "mart.fct_commit", label: "fact_commitment_use_daily", sub: "fact (daily)", layer: 4, row: 1, kind: "mart" },
    { id: "mart.fct_anom", label: "fact_anomaly", sub: "fact (per event)", layer: 4, row: 2, kind: "mart" },
    { id: "mart.fct_budget", label: "fact_budget_actual", sub: "fact (period)", layer: 4, row: 3, kind: "mart" },
    { id: "mart.dim_svc", label: "dim_service", sub: "dim (table)", layer: 4, row: 4, kind: "mart" },
    { id: "kpi.unit", label: "Cost per Active User", sub: "fo.kpi.unit_cost", layer: 5, row: 0, kind: "kpi" },
    { id: "kpi.tag", label: "Tag Coverage", sub: "fo.kpi.tag_coverage", layer: 5, row: 1, kind: "kpi" },
    { id: "kpi.cov", label: "Commit Coverage", sub: "fo.kpi.savings_plan_coverage", layer: 5, row: 2, kind: "kpi" },
    { id: "kpi.idle", label: "Idle Spend", sub: "fo.kpi.idle_spend", layer: 5, row: 3, kind: "kpi" },
    { id: "kpi.var", label: "Budget Variance", sub: "fo.kpi.budget_variance", layer: 5, row: 4, kind: "kpi" },
  ],
  edges: [
    { from: "src.aws", to: "stg.charge" },
    { from: "src.azure", to: "stg.charge" },
    { from: "src.gcp", to: "stg.charge" },
    { from: "src.oci", to: "stg.charge" },
    { from: "src.opencost", to: "stg.tag" },
    { from: "src.aws", to: "stg.commit" },
    { from: "src.azure", to: "stg.commit" },
    { from: "src.aws", to: "stg.budget" },
    { from: "src.aws", to: "stg.anom" },
    { from: "stg.charge", to: "vault.h_acct" },
    { from: "stg.charge", to: "vault.h_svc" },
    { from: "stg.charge", to: "vault.h_res" },
    { from: "stg.charge", to: "vault.l_charge" },
    { from: "stg.charge", to: "vault.s_charge" },
    { from: "stg.charge", to: "vault.s_acct" },
    { from: "stg.tag", to: "vault.s_tag" },
    { from: "stg.tag", to: "vault.s_res" },
    { from: "stg.commit", to: "vault.h_commit" },
    { from: "stg.commit", to: "vault.s_commit" },
    { from: "vault.l_charge", to: "mart.fct_spend" },
    { from: "vault.s_charge", to: "mart.fct_spend" },
    { from: "vault.s_tag", to: "mart.fct_spend" },
    { from: "vault.s_commit", to: "mart.fct_commit" },
    { from: "stg.anom", to: "mart.fct_anom" },
    { from: "stg.budget", to: "mart.fct_budget" },
    { from: "vault.h_svc", to: "mart.dim_svc" },
    { from: "mart.fct_spend", to: "kpi.unit" },
    { from: "mart.fct_spend", to: "kpi.tag" },
    { from: "mart.fct_commit", to: "kpi.cov" },
    { from: "mart.fct_spend", to: "kpi.idle" },
    { from: "mart.fct_budget", to: "kpi.var" },
  ],
};

// ---------------------------------------------------------------------------
// ev_charging  (OCPP 2.0.1 / OCPI 2.2.1 / ISO 15118)
// ---------------------------------------------------------------------------

const evCharging: LineageGraph = {
  title: "EV Charging Operations",
  vertical: "Energy",
  oneLiner:
    "Public and fleet EV charging — OCPP TransactionEvents and OCPI sessions/CDRs through to uptime, utilization, and DR-event compliance KPIs.",
  nodes: [
    { id: "src.cp", label: "ChargePoint Network", sub: "CPO Platform", layer: 0, row: 0, kind: "source" },
    { id: "src.driivz", label: "Driivz EV Mgmt", sub: "CPO Platform", layer: 0, row: 1, kind: "source" },
    { id: "src.ampeco", label: "AMPECO", sub: "CPO Platform", layer: 0, row: 2, kind: "source" },
    { id: "src.hubject", label: "Hubject intercharge", sub: "Roaming Hub (OCPI)", layer: 0, row: 3, kind: "source" },
    { id: "src.abb", label: "ABB / Wallbox", sub: "Hardware", layer: 0, row: 4, kind: "source" },
    { id: "stg.session", label: "stg_session", sub: "OCPI Session", layer: 1, row: 0, kind: "stage" },
    { id: "stg.txevt", label: "stg_transaction_event", sub: "OCPP TransactionEvent", layer: 1, row: 1, kind: "stage" },
    { id: "stg.mv", label: "stg_meter_value", sub: "OCPP MeterValues", layer: 1, row: 2, kind: "stage" },
    { id: "stg.cdr", label: "stg_cdr", sub: "OCPI CDR", layer: 1, row: 3, kind: "stage" },
    { id: "stg.status", label: "stg_status_notification", sub: "OCPP StatusNotification", layer: 1, row: 4, kind: "stage" },
    { id: "vault.h_loc", label: "hub_location", sub: "Vault hub", layer: 2, row: 0, kind: "vault" },
    { id: "vault.h_evse", label: "hub_evse", sub: "Vault hub", layer: 2, row: 1, kind: "vault" },
    { id: "vault.h_token", label: "hub_token", sub: "Vault hub", layer: 2, row: 2, kind: "vault" },
    { id: "vault.h_session", label: "hub_session", sub: "Vault hub", layer: 2, row: 3, kind: "vault" },
    { id: "vault.l_assets", label: "link_session_assets", sub: "Vault link", layer: 2, row: 4, kind: "vault" },
    { id: "vault.s_station", label: "sat_station_state", sub: "Vault sat", layer: 3, row: 0, kind: "vault" },
    { id: "vault.s_evse", label: "sat_evse_status", sub: "Vault sat", layer: 3, row: 1, kind: "vault" },
    { id: "vault.s_session", label: "sat_session_state", sub: "Vault sat", layer: 3, row: 2, kind: "vault" },
    { id: "vault.s_mv", label: "sat_meter_value", sub: "Vault sat", layer: 3, row: 3, kind: "vault" },
    { id: "vault.s_cdr", label: "sat_cdr", sub: "Vault sat", layer: 3, row: 4, kind: "vault" },
    { id: "mart.fct_session", label: "fact_session", sub: "fact (per session)", layer: 4, row: 0, kind: "mart" },
    { id: "mart.fct_cdr", label: "fact_cdr", sub: "fact (per CDR)", layer: 4, row: 1, kind: "mart" },
    { id: "mart.fct_evse", label: "fact_evse_status_15m", sub: "fact (15m)", layer: 4, row: 2, kind: "mart" },
    { id: "mart.fct_dr", label: "fact_dr_response", sub: "fact (per event)", layer: 4, row: 3, kind: "mart" },
    { id: "mart.dim_evse", label: "dim_evse", sub: "dim (table)", layer: 4, row: 4, kind: "mart" },
    { id: "kpi.uptime", label: "Charger Uptime", sub: "ev.kpi.uptime", layer: 5, row: 0, kind: "kpi" },
    { id: "kpi.util", label: "Connector Utilization", sub: "ev.kpi.utilization", layer: 5, row: 1, kind: "kpi" },
    { id: "kpi.kwh", label: "kWh per Session", sub: "ev.kpi.kwh_per_session", layer: 5, row: 2, kind: "kpi" },
    { id: "kpi.succ", label: "Session Success Rate", sub: "ev.kpi.session_success_rate", layer: 5, row: 3, kind: "kpi" },
    { id: "kpi.dr", label: "DR Event Compliance", sub: "ev.kpi.dr_event_compliance", layer: 5, row: 4, kind: "kpi" },
  ],
  edges: [
    { from: "src.cp", to: "stg.session" },
    { from: "src.driivz", to: "stg.session" },
    { from: "src.ampeco", to: "stg.txevt" },
    { from: "src.abb", to: "stg.txevt" },
    { from: "src.abb", to: "stg.mv" },
    { from: "src.hubject", to: "stg.cdr" },
    { from: "src.cp", to: "stg.cdr" },
    { from: "src.abb", to: "stg.status" },
    { from: "stg.session", to: "vault.h_session" },
    { from: "stg.session", to: "vault.s_session" },
    { from: "stg.session", to: "vault.l_assets" },
    { from: "stg.txevt", to: "vault.s_session" },
    { from: "stg.mv", to: "vault.s_mv" },
    { from: "stg.cdr", to: "vault.s_cdr" },
    { from: "stg.status", to: "vault.s_evse" },
    { from: "stg.status", to: "vault.s_station" },
    { from: "vault.h_loc", to: "vault.l_assets" },
    { from: "vault.h_evse", to: "vault.l_assets" },
    { from: "vault.h_token", to: "vault.l_assets" },
    { from: "vault.l_assets", to: "mart.fct_session" },
    { from: "vault.s_session", to: "mart.fct_session" },
    { from: "vault.s_mv", to: "mart.fct_session" },
    { from: "vault.s_cdr", to: "mart.fct_cdr" },
    { from: "vault.s_evse", to: "mart.fct_evse" },
    { from: "vault.s_station", to: "mart.fct_dr" },
    { from: "vault.h_evse", to: "mart.dim_evse" },
    { from: "mart.fct_evse", to: "kpi.uptime" },
    { from: "mart.fct_session", to: "kpi.util" },
    { from: "mart.fct_session", to: "kpi.kwh" },
    { from: "mart.fct_session", to: "kpi.succ" },
    { from: "mart.fct_dr", to: "kpi.dr" },
  ],
};

// ---------------------------------------------------------------------------
// tax_administration  (IRS MeF / EFW2 / OECD CRS / FATCA)
// ---------------------------------------------------------------------------

const taxAdministration: LineageGraph = {
  title: "Tax Administration",
  vertical: "Public Sector",
  oneLiner:
    "Citizen and business tax filing — MeF returns, 1099/W-2 information returns, audit cases, and CRS exchange feeding voluntary compliance, refund cycle, and AUR match KPIs.",
  nodes: [
    { id: "src.gentax", label: "Fast Enterprises GenTax", sub: "Tax Platform", layer: 0, row: 0, kind: "source" },
    { id: "src.sap", label: "SAP TRM", sub: "Tax Platform", layer: 0, row: 1, kind: "source" },
    { id: "src.revhub", label: "RSI REVHUB", sub: "Tax Platform", layer: 0, row: 2, kind: "source" },
    { id: "src.imf", label: "IRS IMF/BMF", sub: "Mainframe legacy", layer: 0, row: 3, kind: "source" },
    { id: "src.onesrc", label: "Thomson Reuters ONESOURCE", sub: "Compliance", layer: 0, row: 4, kind: "source" },
    { id: "stg.return", label: "stg_return", sub: "MeF ReturnHeader/Data", layer: 1, row: 0, kind: "stage" },
    { id: "stg.form", label: "stg_form", sub: "1040/1120/1065/941", layer: 1, row: 1, kind: "stage" },
    { id: "stg.info", label: "stg_information_return", sub: "1099 / W-2", layer: 1, row: 2, kind: "stage" },
    { id: "stg.audit", label: "stg_audit_case", sub: "view", layer: 1, row: 3, kind: "stage" },
    { id: "stg.crs", label: "stg_crs_record", sub: "OECD CRS XML", layer: 1, row: 4, kind: "stage" },
    { id: "vault.h_tp", label: "hub_taxpayer", sub: "Vault hub (TIN)", layer: 2, row: 0, kind: "vault" },
    { id: "vault.h_ret", label: "hub_return", sub: "Vault hub", layer: 2, row: 1, kind: "vault" },
    { id: "vault.h_audit", label: "hub_audit_case", sub: "Vault hub", layer: 2, row: 2, kind: "vault" },
    { id: "vault.h_info", label: "hub_information_return", sub: "Vault hub", layer: 2, row: 3, kind: "vault" },
    { id: "vault.l_tp_ret", label: "link_taxpayer_return", sub: "Vault link", layer: 2, row: 4, kind: "vault" },
    { id: "vault.s_tp", label: "sat_taxpayer_descriptive", sub: "Vault sat", layer: 3, row: 0, kind: "vault" },
    { id: "vault.s_ret", label: "sat_return_state", sub: "Vault sat", layer: 3, row: 1, kind: "vault" },
    { id: "vault.s_data", label: "sat_return_data", sub: "Vault sat", layer: 3, row: 2, kind: "vault" },
    { id: "vault.s_audit", label: "sat_audit_state", sub: "Vault sat", layer: 3, row: 3, kind: "vault" },
    { id: "vault.s_info", label: "sat_information_return", sub: "Vault sat", layer: 3, row: 4, kind: "vault" },
    { id: "mart.fct_filing", label: "fact_filing_daily", sub: "fact (daily)", layer: 4, row: 0, kind: "mart" },
    { id: "mart.fct_refund", label: "fact_refund", sub: "fact (per refund)", layer: 4, row: 1, kind: "mart" },
    { id: "mart.fct_audit", label: "fact_audit_outcome", sub: "fact (per case)", layer: 4, row: 2, kind: "mart" },
    { id: "mart.fct_aur", label: "fact_aur_match", sub: "fact (per match)", layer: 4, row: 3, kind: "mart" },
    { id: "mart.fct_lien", label: "fact_lien_aging", sub: "fact (snap)", layer: 4, row: 4, kind: "mart" },
    { id: "kpi.vc", label: "Voluntary Compliance", sub: "tax.kpi.voluntary_compliance", layer: 5, row: 0, kind: "kpi" },
    { id: "kpi.refund", label: "Refund Cycle Time", sub: "tax.kpi.refund_cycle_time", layer: 5, row: 1, kind: "kpi" },
    { id: "kpi.fraud", label: "Fraud Detection Rate", sub: "tax.kpi.fraud_detection", layer: 5, row: 2, kind: "kpi" },
    { id: "kpi.aur", label: "AUR Match Rate", sub: "tax.kpi.aur_match_rate", layer: 5, row: 3, kind: "kpi" },
    { id: "kpi.efile", label: "e-File Adoption", sub: "tax.kpi.efile_rate", layer: 5, row: 4, kind: "kpi" },
  ],
  edges: [
    { from: "src.gentax", to: "stg.return" },
    { from: "src.sap", to: "stg.return" },
    { from: "src.revhub", to: "stg.form" },
    { from: "src.imf", to: "stg.form" },
    { from: "src.imf", to: "stg.info" },
    { from: "src.gentax", to: "stg.audit" },
    { from: "src.onesrc", to: "stg.crs" },
    { from: "stg.return", to: "vault.h_ret" },
    { from: "stg.return", to: "vault.s_ret" },
    { from: "stg.return", to: "vault.s_data" },
    { from: "stg.return", to: "vault.h_tp" },
    { from: "stg.return", to: "vault.s_tp" },
    { from: "stg.return", to: "vault.l_tp_ret" },
    { from: "stg.info", to: "vault.h_info" },
    { from: "stg.info", to: "vault.s_info" },
    { from: "stg.audit", to: "vault.h_audit" },
    { from: "stg.audit", to: "vault.s_audit" },
    { from: "vault.h_tp", to: "vault.l_tp_ret" },
    { from: "vault.l_tp_ret", to: "mart.fct_filing" },
    { from: "vault.s_ret", to: "mart.fct_filing" },
    { from: "vault.s_data", to: "mart.fct_refund" },
    { from: "vault.s_audit", to: "mart.fct_audit" },
    { from: "vault.s_info", to: "mart.fct_aur" },
    { from: "vault.s_data", to: "mart.fct_aur" },
    { from: "vault.s_tp", to: "mart.fct_lien" },
    { from: "mart.fct_filing", to: "kpi.vc" },
    { from: "mart.fct_refund", to: "kpi.refund" },
    { from: "mart.fct_refund", to: "kpi.fraud" },
    { from: "mart.fct_aur", to: "kpi.aur" },
    { from: "mart.fct_filing", to: "kpi.efile" },
  ],
};

// ---------------------------------------------------------------------------
// real_world_evidence  (OMOP CDM v5.4)
// ---------------------------------------------------------------------------

const realWorldEvidence: LineageGraph = {
  title: "Real-World Evidence",
  vertical: "Life Sciences",
  oneLiner:
    "Curated EHR + claims + registry data — OMOP CDM v5.4 standard concepts feeding cohort definition, outcomes, and HEOR studies.",
  nodes: [
    { id: "src.iqvia", label: "IQVIA PharMetrics+", sub: "RWD (claims)", layer: 0, row: 0, kind: "source" },
    { id: "src.optum", label: "Optum Clinformatics", sub: "RWD (claims+EHR)", layer: 0, row: 1, kind: "source" },
    { id: "src.flatiron", label: "Flatiron OncoEMR", sub: "Oncology RWD", layer: 0, row: 2, kind: "source" },
    { id: "src.komodo", label: "Komodo Healthcare Map", sub: "RWD Platform", layer: 0, row: 3, kind: "source" },
    { id: "src.athena", label: "OHDSI Athena", sub: "Vocabulary", layer: 0, row: 4, kind: "source" },
    { id: "stg.person", label: "stg_person", sub: "OMOP PERSON", layer: 1, row: 0, kind: "stage" },
    { id: "stg.visit", label: "stg_visit_occurrence", sub: "OMOP VISIT", layer: 1, row: 1, kind: "stage" },
    { id: "stg.cond", label: "stg_condition_occurrence", sub: "OMOP CONDITION", layer: 1, row: 2, kind: "stage" },
    { id: "stg.drug", label: "stg_drug_exposure", sub: "OMOP DRUG_EXPOSURE", layer: 1, row: 3, kind: "stage" },
    { id: "stg.meas", label: "stg_measurement", sub: "OMOP MEASUREMENT", layer: 1, row: 4, kind: "stage" },
    { id: "vault.h_person", label: "hub_person", sub: "Vault hub", layer: 2, row: 0, kind: "vault" },
    { id: "vault.h_visit", label: "hub_visit", sub: "Vault hub", layer: 2, row: 1, kind: "vault" },
    { id: "vault.h_concept", label: "hub_concept", sub: "Vault hub (Athena)", layer: 2, row: 2, kind: "vault" },
    { id: "vault.l_visit", label: "link_visit_person", sub: "Vault link", layer: 2, row: 3, kind: "vault" },
    { id: "vault.l_drug", label: "link_drug_person", sub: "Vault link", layer: 2, row: 4, kind: "vault" },
    { id: "vault.s_person", label: "sat_person_demographics", sub: "Vault sat", layer: 3, row: 0, kind: "vault" },
    { id: "vault.s_visit", label: "sat_visit_state", sub: "Vault sat", layer: 3, row: 1, kind: "vault" },
    { id: "vault.s_cond", label: "sat_condition_state", sub: "Vault sat", layer: 3, row: 2, kind: "vault" },
    { id: "vault.s_drug", label: "sat_drug_exposure", sub: "Vault sat", layer: 3, row: 3, kind: "vault" },
    { id: "vault.s_meas", label: "sat_measurement_value", sub: "Vault sat", layer: 3, row: 4, kind: "vault" },
    { id: "mart.fct_visit", label: "fact_visit", sub: "fact (per visit)", layer: 4, row: 0, kind: "mart" },
    { id: "mart.fct_cond", label: "fact_condition", sub: "fact (per dx)", layer: 4, row: 1, kind: "mart" },
    { id: "mart.fct_drug", label: "fact_drug_exposure", sub: "fact (per exposure)", layer: 4, row: 2, kind: "mart" },
    { id: "mart.fct_cohort", label: "fact_cohort_membership", sub: "fact (per person/cohort)", layer: 4, row: 3, kind: "mart" },
    { id: "mart.fct_meas", label: "fact_measurement", sub: "fact (per measure)", layer: 4, row: 4, kind: "mart" },
    { id: "kpi.cohort", label: "Cohort Match Rate", sub: "rwe.kpi.cohort_match", layer: 5, row: 0, kind: "kpi" },
    { id: "kpi.fresh", label: "Data Freshness", sub: "rwe.kpi.data_freshness", layer: 5, row: 1, kind: "kpi" },
    { id: "kpi.link", label: "Cross-Source Linkage", sub: "rwe.kpi.linkage_rate", layer: 5, row: 2, kind: "kpi" },
    { id: "kpi.std", label: "Standard Concept Coverage", sub: "rwe.kpi.standard_concept_coverage", layer: 5, row: 3, kind: "kpi" },
    { id: "kpi.dq", label: "Achilles DQ Pass Rate", sub: "rwe.kpi.dq_check_pass", layer: 5, row: 4, kind: "kpi" },
  ],
  edges: [
    { from: "src.iqvia", to: "stg.person" },
    { from: "src.optum", to: "stg.person" },
    { from: "src.flatiron", to: "stg.visit" },
    { from: "src.optum", to: "stg.visit" },
    { from: "src.komodo", to: "stg.cond" },
    { from: "src.iqvia", to: "stg.drug" },
    { from: "src.flatiron", to: "stg.meas" },
    { from: "src.athena", to: "vault.h_concept" },
    { from: "stg.person", to: "vault.h_person" },
    { from: "stg.person", to: "vault.s_person" },
    { from: "stg.visit", to: "vault.h_visit" },
    { from: "stg.visit", to: "vault.l_visit" },
    { from: "stg.visit", to: "vault.s_visit" },
    { from: "stg.cond", to: "vault.s_cond" },
    { from: "stg.drug", to: "vault.s_drug" },
    { from: "stg.drug", to: "vault.l_drug" },
    { from: "stg.meas", to: "vault.s_meas" },
    { from: "vault.h_person", to: "vault.l_visit" },
    { from: "vault.h_person", to: "vault.l_drug" },
    { from: "vault.l_visit", to: "mart.fct_visit" },
    { from: "vault.s_visit", to: "mart.fct_visit" },
    { from: "vault.s_cond", to: "mart.fct_cond" },
    { from: "vault.s_drug", to: "mart.fct_drug" },
    { from: "vault.s_person", to: "mart.fct_cohort" },
    { from: "vault.s_meas", to: "mart.fct_meas" },
    { from: "mart.fct_cohort", to: "kpi.cohort" },
    { from: "mart.fct_visit", to: "kpi.fresh" },
    { from: "mart.fct_cohort", to: "kpi.link" },
    { from: "mart.fct_cond", to: "kpi.std" },
    { from: "mart.fct_meas", to: "kpi.dq" },
  ],
};

// ---------------------------------------------------------------------------
// settlement_clearing  (ISO 20022 securities sese.* / DTCC CNS / camt.054)
// ---------------------------------------------------------------------------

const settlementClearing: LineageGraph = {
  title: "Settlement & Clearing",
  vertical: "BFSI",
  oneLiner:
    "Net settlement, multilateral clearing, and reconciliation — ISO 20022 sese.* / DTCC CNS feeding fail rate, recon breaks, and intraday liquidity KPIs.",
  nodes: [
    { id: "src.dtcc", label: "DTCC NSCC CNS / DTC", sub: "CCP / CSD", layer: 0, row: 0, kind: "source" },
    { id: "src.euroclear", label: "Euroclear EB", sub: "CSD", layer: 0, row: 1, kind: "source" },
    { id: "src.clearstream", label: "Clearstream CASCADE", sub: "CSD", layer: 0, row: 2, kind: "source" },
    { id: "src.broadridge", label: "Broadridge Impact", sub: "Post-trade", layer: 0, row: 3, kind: "source" },
    { id: "src.swift", label: "SWIFT gpi", sub: "Messaging Network", layer: 0, row: 4, kind: "source" },
    { id: "stg.ssi", label: "stg_settlement_instruction", sub: "sese.023", layer: 1, row: 0, kind: "stage" },
    { id: "stg.matching", label: "stg_matching_status", sub: "sese.024", layer: 1, row: 1, kind: "stage" },
    { id: "stg.fail", label: "stg_failed_settlement", sub: "view", layer: 1, row: 2, kind: "stage" },
    { id: "stg.margin", label: "stg_margin_call", sub: "colr.* / CCP", layer: 1, row: 3, kind: "stage" },
    { id: "stg.coll", label: "stg_collateral_movement", sub: "view", layer: 1, row: 4, kind: "stage" },
    { id: "vault.h_party", label: "hub_party", sub: "Vault hub (LEI/BIC)", layer: 2, row: 0, kind: "vault" },
    { id: "vault.h_inst", label: "hub_instrument", sub: "Vault hub", layer: 2, row: 1, kind: "vault" },
    { id: "vault.h_ssi", label: "hub_ssi", sub: "Vault hub", layer: 2, row: 2, kind: "vault" },
    { id: "vault.h_ccp", label: "hub_ccp", sub: "Vault hub", layer: 2, row: 3, kind: "vault" },
    { id: "vault.l_mc", label: "link_margin_call_ccp", sub: "Vault link", layer: 2, row: 4, kind: "vault" },
    { id: "vault.s_ssi", label: "sat_ssi_state", sub: "Vault sat", layer: 3, row: 0, kind: "vault" },
    { id: "vault.s_fail", label: "sat_ssi_failure", sub: "Vault sat", layer: 3, row: 1, kind: "vault" },
    { id: "vault.s_keep", label: "sat_safekeeping_balance", sub: "Vault sat", layer: 3, row: 2, kind: "vault" },
    { id: "vault.s_mc", label: "sat_margin_call_state", sub: "Vault sat", layer: 3, row: 3, kind: "vault" },
    { id: "vault.s_cns", label: "sat_cns_obligation", sub: "Vault sat (daily)", layer: 3, row: 4, kind: "vault" },
    { id: "mart.fct_set", label: "fact_settlement", sub: "fact (per SSI)", layer: 4, row: 0, kind: "mart" },
    { id: "mart.fct_fail", label: "fact_settlement_fail", sub: "fact (per fail)", layer: 4, row: 1, kind: "mart" },
    { id: "mart.fct_mc", label: "fact_margin_call", sub: "fact (per call)", layer: 4, row: 2, kind: "mart" },
    { id: "mart.fct_cns", label: "fact_cns_obligation_daily", sub: "fact (daily)", layer: 4, row: 3, kind: "mart" },
    { id: "mart.fct_brk", label: "fact_recon_break_daily", sub: "fact (daily)", layer: 4, row: 4, kind: "mart" },
    { id: "kpi.fail", label: "Settlement Fail Rate", sub: "stl.kpi.fail_rate", layer: 5, row: 0, kind: "kpi" },
    { id: "kpi.same", label: "Same-Day Settlement", sub: "stl.kpi.same_day_settle", layer: 5, row: 1, kind: "kpi" },
    { id: "kpi.brk", label: "Recon Break Count", sub: "stl.kpi.recon_break_count", layer: 5, row: 2, kind: "kpi" },
    { id: "kpi.cns", label: "CNS Compression", sub: "stl.kpi.cns_compression", layer: 5, row: 3, kind: "kpi" },
    { id: "kpi.liq", label: "Intraday Liquidity Use", sub: "stl.kpi.intraday_liquidity_use", layer: 5, row: 4, kind: "kpi" },
  ],
  edges: [
    { from: "src.dtcc", to: "stg.ssi" },
    { from: "src.euroclear", to: "stg.ssi" },
    { from: "src.clearstream", to: "stg.ssi" },
    { from: "src.swift", to: "stg.matching" },
    { from: "src.broadridge", to: "stg.matching" },
    { from: "src.dtcc", to: "stg.fail" },
    { from: "src.dtcc", to: "stg.margin" },
    { from: "src.broadridge", to: "stg.coll" },
    { from: "stg.ssi", to: "vault.h_ssi" },
    { from: "stg.ssi", to: "vault.s_ssi" },
    { from: "stg.ssi", to: "vault.h_party" },
    { from: "stg.ssi", to: "vault.h_inst" },
    { from: "stg.fail", to: "vault.s_fail" },
    { from: "stg.matching", to: "vault.s_ssi" },
    { from: "stg.margin", to: "vault.l_mc" },
    { from: "stg.margin", to: "vault.s_mc" },
    { from: "stg.coll", to: "vault.s_keep" },
    { from: "vault.h_ccp", to: "vault.l_mc" },
    { from: "vault.h_party", to: "vault.s_cns" },
    { from: "vault.s_ssi", to: "mart.fct_set" },
    { from: "vault.s_fail", to: "mart.fct_fail" },
    { from: "vault.l_mc", to: "mart.fct_mc" },
    { from: "vault.s_mc", to: "mart.fct_mc" },
    { from: "vault.s_cns", to: "mart.fct_cns" },
    { from: "vault.s_keep", to: "mart.fct_brk" },
    { from: "mart.fct_fail", to: "kpi.fail" },
    { from: "mart.fct_set", to: "kpi.same" },
    { from: "mart.fct_brk", to: "kpi.brk" },
    { from: "mart.fct_cns", to: "kpi.cns" },
    { from: "mart.fct_mc", to: "kpi.liq" },
  ],
};

// ---------------------------------------------------------------------------
// programmatic_advertising  (IAB OpenRTB 2.6 / VAST 4.x / AdCOM)
// ---------------------------------------------------------------------------

const programmaticAdvertising: LineageGraph = {
  title: "Programmatic Advertising",
  vertical: "Media",
  oneLiner:
    "Real-time bidded ad transactions — OpenRTB 2.6 BidRequests, AdCOM placements, VAST video events, and verification feeding eCPM, viewability, and IVT KPIs.",
  nodes: [
    { id: "src.gam", label: "Google Ad Manager", sub: "SSP / Ad Server", layer: 0, row: 0, kind: "source" },
    { id: "src.magnite", label: "Magnite SpringServe", sub: "SSP", layer: 0, row: 1, kind: "source" },
    { id: "src.pubmatic", label: "PubMatic OpenWrap", sub: "SSP", layer: 0, row: 2, kind: "source" },
    { id: "src.ttd", label: "The Trade Desk", sub: "DSP", layer: 0, row: 3, kind: "source" },
    { id: "src.ias", label: "IAS / DoubleVerify / HUMAN", sub: "Verification / IVT", layer: 0, row: 4, kind: "source" },
    { id: "stg.req", label: "stg_ad_request", sub: "OpenRTB BidRequest", layer: 1, row: 0, kind: "stage" },
    { id: "stg.bid", label: "stg_bid", sub: "OpenRTB SeatBid.Bid", layer: 1, row: 1, kind: "stage" },
    { id: "stg.imp", label: "stg_impression_event", sub: "view", layer: 1, row: 2, kind: "stage" },
    { id: "stg.video", label: "stg_video_event", sub: "VAST 4.x trackers", layer: 1, row: 3, kind: "stage" },
    { id: "stg.conv", label: "stg_conversion_event", sub: "view", layer: 1, row: 4, kind: "stage" },
    { id: "vault.h_req", label: "hub_ad_request", sub: "Vault hub", layer: 2, row: 0, kind: "vault" },
    { id: "vault.h_imp", label: "hub_imp", sub: "Vault hub", layer: 2, row: 1, kind: "vault" },
    { id: "vault.h_bid", label: "hub_bid", sub: "Vault hub", layer: 2, row: 2, kind: "vault" },
    { id: "vault.h_camp", label: "hub_campaign", sub: "Vault hub", layer: 2, row: 3, kind: "vault" },
    { id: "vault.l_bid_imp", label: "link_bid_imp", sub: "Vault link", layer: 2, row: 4, kind: "vault" },
    { id: "vault.s_ctx", label: "sat_request_context", sub: "Vault sat (Site/App/Device)", layer: 3, row: 0, kind: "vault" },
    { id: "vault.s_place", label: "sat_imp_placement", sub: "Vault sat (AdCOM)", layer: 3, row: 1, kind: "vault" },
    { id: "vault.s_bid", label: "sat_bid_state", sub: "Vault sat", layer: 3, row: 2, kind: "vault" },
    { id: "vault.s_out", label: "sat_bid_outcome", sub: "Vault sat", layer: 3, row: 3, kind: "vault" },
    { id: "vault.s_user", label: "sat_user_consent", sub: "Vault sat (GPP/TCF)", layer: 3, row: 4, kind: "vault" },
    { id: "mart.fct_bid", label: "fact_bid", sub: "fact (per bid)", layer: 4, row: 0, kind: "mart" },
    { id: "mart.fct_imp", label: "fact_impression", sub: "fact (per imp)", layer: 4, row: 1, kind: "mart" },
    { id: "mart.fct_video", label: "fact_video_event", sub: "fact (per event)", layer: 4, row: 2, kind: "mart" },
    { id: "mart.fct_conv", label: "fact_conversion", sub: "fact (per conv)", layer: 4, row: 3, kind: "mart" },
    { id: "mart.fct_auc", label: "fact_auction_summary_hourly", sub: "fact (hourly)", layer: 4, row: 4, kind: "mart" },
    { id: "kpi.fill", label: "Fill Rate", sub: "prog.kpi.fill_rate", layer: 5, row: 0, kind: "kpi" },
    { id: "kpi.ecpm", label: "Effective CPM", sub: "prog.kpi.ecpm", layer: 5, row: 1, kind: "kpi" },
    { id: "kpi.view", label: "MRC Viewability", sub: "prog.kpi.viewability", layer: 5, row: 2, kind: "kpi" },
    { id: "kpi.ivt", label: "Invalid Traffic Rate", sub: "prog.kpi.ivt_rate", layer: 5, row: 3, kind: "kpi" },
    { id: "kpi.lat", label: "Bid Latency P95", sub: "prog.kpi.bid_response_latency", layer: 5, row: 4, kind: "kpi" },
  ],
  edges: [
    { from: "src.gam", to: "stg.req" },
    { from: "src.magnite", to: "stg.req" },
    { from: "src.pubmatic", to: "stg.req" },
    { from: "src.ttd", to: "stg.bid" },
    { from: "src.gam", to: "stg.imp" },
    { from: "src.magnite", to: "stg.video" },
    { from: "src.gam", to: "stg.conv" },
    { from: "src.ias", to: "stg.imp" },
    { from: "stg.req", to: "vault.h_req" },
    { from: "stg.req", to: "vault.s_ctx" },
    { from: "stg.req", to: "vault.s_user" },
    { from: "stg.bid", to: "vault.h_bid" },
    { from: "stg.bid", to: "vault.s_bid" },
    { from: "stg.bid", to: "vault.s_out" },
    { from: "stg.imp", to: "vault.h_imp" },
    { from: "stg.imp", to: "vault.s_place" },
    { from: "vault.h_bid", to: "vault.l_bid_imp" },
    { from: "vault.h_imp", to: "vault.l_bid_imp" },
    { from: "vault.s_bid", to: "mart.fct_bid" },
    { from: "vault.s_out", to: "mart.fct_bid" },
    { from: "vault.l_bid_imp", to: "mart.fct_imp" },
    { from: "vault.s_place", to: "mart.fct_imp" },
    { from: "stg.video", to: "mart.fct_video" },
    { from: "stg.conv", to: "mart.fct_conv" },
    { from: "vault.h_req", to: "mart.fct_auc" },
    { from: "mart.fct_imp", to: "kpi.fill" },
    { from: "mart.fct_imp", to: "kpi.ecpm" },
    { from: "mart.fct_imp", to: "kpi.view" },
    { from: "mart.fct_imp", to: "kpi.ivt" },
    { from: "mart.fct_bid", to: "kpi.lat" },
  ],
};

export const anchorLineages: Record<AnchorKey, LineageGraph> = {
  payments,
  p_and_c_claims: pAndCClaims,
  merchandising,
  demand_planning: demandPlanning,
  hotel_revenue_management: hotelRevenueManagement,
  mes_quality: mesQuality,
  pharmacovigilance,
  ehr_integrations: ehrIntegrations,
  capital_markets: capitalMarkets,
  smart_metering: smartMetering,
  clinical_trials: clinicalTrials,
  cloud_finops: cloudFinops,
  ev_charging: evCharging,
  tax_administration: taxAdministration,
  real_world_evidence: realWorldEvidence,
  settlement_clearing: settlementClearing,
  programmatic_advertising: programmaticAdvertising,
};

// Slug used in the URL — same as the AnchorKey but we keep them aligned
// so that the registry's subdomain id (which uses underscores) maps cleanly.
export const anchorSlugs: Record<AnchorKey, string> = {
  payments: "payments",
  p_and_c_claims: "p_and_c_claims",
  merchandising: "merchandising",
  demand_planning: "demand_planning",
  hotel_revenue_management: "hotel_revenue_management",
  mes_quality: "mes_quality",
  pharmacovigilance: "pharmacovigilance",
  ehr_integrations: "ehr_integrations",
  capital_markets: "capital_markets",
  smart_metering: "smart_metering",
  clinical_trials: "clinical_trials",
  cloud_finops: "cloud_finops",
  ev_charging: "ev_charging",
  tax_administration: "tax_administration",
  real_world_evidence: "real_world_evidence",
  settlement_clearing: "settlement_clearing",
  programmatic_advertising: "programmatic_advertising",
};
