"""Generate 36 new compact subdomain YAML files for Domain Explorer.

Run once during this finalization pass; can be safely re-run (idempotent overwrite).
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "taxonomy"

# (id, name, vertical, oneLiner,
#  [personas: (name, title, level)],
#  [kpis:    (id, name, formula, unit, direction)],
#  [sources: (vendor, product, category)],
#  [conns:   (type, protocol, auth)],
#  [entities:(name, description)])
NEW = [
    # ---------------- Insurance ----------------
    ("underwriting", "Underwriting", "Insurance",
     "Risk selection, pricing, and policy issuance across personal, commercial, and specialty lines.",
     [("Chief Underwriter", "Chief Underwriter", "C-suite"),
      ("UW Manager", "Underwriting Manager", "Manager"),
      ("Pricing Actuary", "Pricing Actuary", "IC")],
     [("uw.kpi.hit_ratio", "Quote-to-Bind Hit Ratio", "bound / quoted", "%", "higher_is_better"),
      ("uw.kpi.loss_ratio", "Loss Ratio", "losses / earned_premium", "%", "lower_is_better"),
      ("uw.kpi.cycle_time", "UW Cycle Time", "avg(decision_ts - submitted_ts)", "hours", "lower_is_better"),
      ("uw.kpi.declination_rate", "Declination Rate", "declined / submissions", "%", "target_band"),
      ("uw.kpi.referral_rate", "Referral Rate", "referred / submissions", "%", "lower_is_better")],
     [("Duck Creek", "Underwriting", "Policy Admin"),
      ("Guidewire", "PolicyCenter", "Policy Admin"),
      ("Verisk", "ISO ERC", "Rating Bureau"),
      ("LexisNexis", "RiskClassifier", "External Risk Data"),
      ("Earnix", "Underwrite-It", "Pricing Engine")],
     [("REST", "HTTPS", "OAuth2"),
      ("SOAP", "HTTPS", "WS-Security"),
      ("File feeds", "SFTP", "SSH key")],
     [("Submission", "Quote intake from agent or broker"),
      ("Quote", "Priced quote returned to broker"),
      ("Policy", "Bound policy contract"),
      ("Risk", "Subject of insurance with characteristics"),
      ("Endorsement", "Mid-term policy change"),
      ("RatingFactor", "Lookup factor used in pricing")]),

    ("life_annuity", "Life & Annuity", "Insurance",
     "Life insurance and annuity products covering issuance, in-force servicing, and benefits administration.",
     [("Head of Life", "Head of Life Insurance", "VP"),
      ("Annuity Product Owner", "Annuity Product Owner", "Director"),
      ("Policy Servicing Lead", "Life Policy Servicing Lead", "Manager")],
     [("la.kpi.persistency", "13-month Persistency", "active_at_13m / issued", "%", "higher_is_better"),
      ("la.kpi.surrender_rate", "Surrender Rate", "surrenders / in_force", "%", "lower_is_better"),
      ("la.kpi.new_business_apv", "New Business APV", "sum(annual_premium_value)", "USD", "higher_is_better"),
      ("la.kpi.claim_ratio", "Mortality / Claim Ratio", "claims_paid / earned_premium", "%", "lower_is_better"),
      ("la.kpi.unitlinked_aum", "Unit-Linked AUM", "sum(fund_value)", "USD", "higher_is_better")],
     [("Oracle", "Insurance Policy Admin", "Policy Admin"),
      ("DXC", "wmA", "Life Policy Admin"),
      ("FAST", "Insurance Platform", "Policy Admin"),
      ("Bloomberg", "Terminal", "Asset Pricing"),
      ("Pega", "Customer Service", "Servicing")],
     [("REST", "HTTPS", "OAuth2"),
      ("File feeds", "SFTP", "SSH key"),
      ("MQ", "JMS", "mTLS")],
     [("Policy", "Life or annuity contract"),
      ("Beneficiary", "Designated benefit recipient"),
      ("Premium", "Periodic premium payment"),
      ("Fund", "Linked investment fund"),
      ("Claim", "Death or surrender claim"),
      ("Annuitant", "Annuity payment recipient")]),

    ("claims_subrogation", "Claims & Subrogation", "Insurance",
     "Claims intake, adjudication, recovery, and subrogation across P&C and specialty lines.",
     [("Head of Claims", "Head of Claims", "VP"),
      ("Subrogation Lead", "Subrogation Recovery Lead", "Manager"),
      ("Claims Adjuster", "Senior Claims Adjuster", "IC")],
     [("clm.kpi.cycle_time", "Claim Cycle Time", "avg(closed_ts - opened_ts)", "days", "lower_is_better"),
      ("clm.kpi.subrogation_recovery", "Subrogation Recovery Rate", "recovered / recoverable", "%", "higher_is_better"),
      ("clm.kpi.lae_ratio", "LAE Ratio", "lae / loss", "%", "lower_is_better"),
      ("clm.kpi.reopen_rate", "Reopen Rate", "reopened / closed", "%", "lower_is_better"),
      ("clm.kpi.fraud_referral", "Fraud Referral Rate", "referred / claims", "%", "target_band")],
     [("Guidewire", "ClaimCenter", "Claims"),
      ("Sapiens", "ClaimsPro", "Claims"),
      ("Mitchell", "WorkCenter", "Claims Adjudication"),
      ("CCC", "Estimating", "Auto Claims"),
      ("ISO", "ClaimSearch", "Industry Data")],
     [("REST", "HTTPS", "OAuth2"),
      ("EDI 837", "SFTP", "SSH key"),
      ("File feeds", "SFTP", "SSH key")],
     [("Claim", "Loss notification and adjudication record"),
      ("Reserve", "Estimated future payment"),
      ("Payment", "Indemnity or expense payment"),
      ("Recovery", "Subrogated or salvaged amount"),
      ("Adjuster", "Person handling the claim"),
      ("LossEvent", "Event triggering claim")]),

    ("reinsurance", "Reinsurance", "Insurance",
     "Treaty and facultative reinsurance ceded to balance net retention and capital.",
     [("Head of Reinsurance", "Head of Reinsurance", "VP"),
      ("Treaty Manager", "Treaty Manager", "Director"),
      ("Cedent Accountant", "Reinsurance Accountant", "Manager")],
     [("re.kpi.ceded_ratio", "Ceded Premium Ratio", "ceded / gross_premium", "%", "target_band"),
      ("re.kpi.recoverables", "Reinsurance Recoverables", "sum(recoverable)", "USD", "higher_is_better"),
      ("re.kpi.commission_ratio", "Ceding Commission Ratio", "commission / ceded_premium", "%", "target_band"),
      ("re.kpi.dso", "Reinsurer DSO", "avg(days_outstanding)", "days", "lower_is_better"),
      ("re.kpi.cat_concentration", "CAT Concentration", "largest_treaty / total", "%", "lower_is_better")],
     [("SAP", "FS-RI", "Reinsurance"),
      ("DXC", "SICS", "Reinsurance"),
      ("Sapiens", "ReinsuranceMaster", "Reinsurance"),
      ("Bermuda Stat", "Filings", "Regulatory"),
      ("AIR Worldwide", "Touchstone", "CAT Modeling")],
     [("REST", "HTTPS", "OAuth2"),
      ("File feeds", "SFTP", "SSH key"),
      ("EDI", "SFTP", "SSH key")],
     [("Treaty", "Reinsurance treaty contract"),
      ("Cession", "Premium cession by treaty"),
      ("Recovery", "Reinsurance recovery on a claim"),
      ("Reinsurer", "Counterparty reinsurer"),
      ("Layer", "Reinsurance layer with attachment and limit"),
      ("Bordereau", "Periodic statement of cessions")]),

    ("actuarial_pricing", "Actuarial Pricing", "Insurance",
     "Actuarial reserving, pricing models, and capital adequacy across lines of business.",
     [("Chief Actuary", "Chief Actuary", "C-suite"),
      ("Pricing Actuary", "Pricing Actuary", "Manager"),
      ("Reserving Actuary", "Reserving Actuary", "Manager")],
     [("act.kpi.combined_ratio", "Combined Ratio", "(losses + expenses)/earned_premium", "%", "lower_is_better"),
      ("act.kpi.scr_ratio", "Solvency Capital Ratio", "own_funds / scr", "%", "higher_is_better"),
      ("act.kpi.reserve_strengthening", "Reserve Strengthening", "prior_year_dev / reserves", "%", "lower_is_better"),
      ("act.kpi.rate_change", "Rate Change", "new_rate / old_rate - 1", "%", "target_band"),
      ("act.kpi.pricing_lift", "Model Pricing Lift", "gini_coefficient", "ratio", "higher_is_better")],
     [("Milliman", "Arius", "Reserving"),
      ("WTW", "ResQ", "Reserving"),
      ("Earnix", "Price-It", "Pricing Engine"),
      ("RGA", "Capital Models", "Capital Modeling"),
      ("Moody's", "AXIS", "Capital & Reserving")],
     [("REST", "HTTPS", "OAuth2"),
      ("File feeds", "SFTP", "SSH key"),
      ("ODBC", "TCP", "DB cred")],
     [("Reserve", "Loss reserve estimate"),
      ("RateClass", "Pricing class with relativity"),
      ("ExperienceTriangle", "Loss development triangle"),
      ("ModelRun", "Versioned pricing or reserving run"),
      ("CapitalScenario", "Stress-test capital scenario")]),

    ("policy_admin", "Policy Administration", "Insurance",
     "Core policy lifecycle: issuance, billing, endorsements, renewals, and cancellations across LOBs.",
     [("Head of Policy Admin", "Head of Policy Admin", "VP"),
      ("Billing Operations Lead", "Billing Operations Lead", "Manager"),
      ("Renewals Manager", "Renewals Manager", "Manager")],
     [("pa.kpi.renewal_retention", "Renewal Retention", "renewed / eligible", "%", "higher_is_better"),
      ("pa.kpi.billing_dso", "Billing DSO", "avg(days_outstanding)", "days", "lower_is_better"),
      ("pa.kpi.policy_count", "Policies-in-Force", "count(active_policies)", "policies", "higher_is_better"),
      ("pa.kpi.endorsement_volume", "Endorsement Volume", "count(endorsements)", "endorsements", "target_band"),
      ("pa.kpi.cancellation_rate", "Cancellation Rate", "cancelled / in_force", "%", "lower_is_better")],
     [("Guidewire", "PolicyCenter", "Policy Admin"),
      ("Duck Creek", "Policy", "Policy Admin"),
      ("Majesco", "P&C Suite", "Policy Admin"),
      ("Insurity", "Policy Decisions", "Policy Admin"),
      ("Stripe", "Billing", "Billing Platform")],
     [("REST", "HTTPS", "OAuth2"),
      ("SOAP", "HTTPS", "WS-Security"),
      ("File feeds", "SFTP", "SSH key")],
     [("Policy", "Active policy contract"),
      ("Endorsement", "Mid-term change to policy"),
      ("Renewal", "Renewal offer and outcome"),
      ("Invoice", "Premium invoice"),
      ("Payment", "Premium payment"),
      ("Cancellation", "Cancellation event")]),

    # ---------------- BFSI additions ----------------
    ("cross_border_payments", "Cross-Border Payments", "BFSI",
     "FX-aware international remittances using SWIFT, RTP, and stablecoin rails.",
     [("Head of Global Payments", "Head of Global Payments", "VP"),
      ("FX Operations Lead", "FX Operations Lead", "Director"),
      ("Correspondent Banking Manager", "Correspondent Banking Manager", "Manager")],
     [("xb.kpi.straight_through", "Cross-Border STP", "stp_count / total", "%", "higher_is_better"),
      ("xb.kpi.fx_spread", "FX Spread Captured", "spread_bps", "bps", "higher_is_better"),
      ("xb.kpi.settlement_time", "Cross-Border Settlement Time", "avg(settled - sent)", "hours", "lower_is_better"),
      ("xb.kpi.repair_rate", "Repair Rate", "repaired / total", "%", "lower_is_better"),
      ("xb.kpi.compliance_holds", "Compliance Holds", "held / sent", "%", "lower_is_better")],
     [("SWIFT", "gpi", "Messaging Network"),
      ("Wise", "Wise Platform", "Payment Provider"),
      ("Citi", "WorldLink", "Correspondent Banking"),
      ("JPM", "Coin", "Tokenized Settlement"),
      ("Currencycloud", "Platform", "FX & Remittance")],
     [("SWIFT MT/ISO20022", "MQ/file", "PKI"),
      ("REST", "HTTPS", "OAuth2"),
      ("File feeds", "SFTP", "SSH key")],
     [("Remittance", "Cross-border payment instruction"),
      ("CorrespondentBank", "Nostro/vostro counterparty"),
      ("FxRate", "Reference and dealt rate"),
      ("ComplianceHold", "OFAC/sanctions hold record"),
      ("NostroBalance", "Nostro account balance")]),

    ("prepaid_cards", "Prepaid Cards", "BFSI",
     "Open and closed-loop prepaid card programs spanning gift, payroll, and benefits.",
     [("Head of Prepaid", "Head of Prepaid", "VP"),
      ("Program Manager", "Program Manager", "Manager"),
      ("Compliance Officer", "Compliance Officer", "Manager")],
     [("pp.kpi.load_volume", "Load Volume", "sum(loads)", "USD", "higher_is_better"),
      ("pp.kpi.breakage", "Breakage Rate", "unspent / loaded", "%", "target_band"),
      ("pp.kpi.activation_rate", "Activation Rate", "activated / issued", "%", "higher_is_better"),
      ("pp.kpi.fraud_loss_bps", "Fraud Loss BPS", "fraud_loss / spend", "bps", "lower_is_better"),
      ("pp.kpi.cards_in_force", "Cards In Force", "count(active_cards)", "cards", "higher_is_better")],
     [("Galileo", "Processing", "Card Processor"),
      ("Marqeta", "Platform", "Card Processor"),
      ("i2c", "Issuer Processing", "Card Processor"),
      ("Visa", "DPS", "Scheme Network"),
      ("Mastercard", "Send", "Disbursement Rail")],
     [("REST", "HTTPS", "OAuth2"),
      ("ISO8583", "TCP", "PKI/MAC"),
      ("File feeds", "SFTP", "SSH key")],
     [("PrepaidCard", "Prepaid card account"),
      ("Load", "Funding load event"),
      ("Spend", "Authorized spend"),
      ("Program", "Issuer program definition"),
      ("KycResult", "KYC outcome on cardholder")]),

    ("merchant_acquiring", "Merchant Acquiring", "BFSI",
     "Onboarding, underwriting, and settlement of card-accepting merchants across MCCs.",
     [("Head of Acquiring", "Head of Acquiring", "VP"),
      ("Risk & Underwriting Lead", "Merchant Risk Lead", "Director"),
      ("Settlement Operations", "Settlement Operations Lead", "Manager")],
     [("ma.kpi.processed_volume", "Processed Volume", "sum(amount)", "USD", "higher_is_better"),
      ("ma.kpi.attrition", "Merchant Attrition", "churned / active", "%", "lower_is_better"),
      ("ma.kpi.chargeback_ratio", "Chargeback Ratio", "chargebacks / sales", "%", "lower_is_better"),
      ("ma.kpi.merchant_mdr", "Merchant Discount Rate", "fees / volume", "bps", "target_band"),
      ("ma.kpi.boarding_tat", "Merchant Boarding TAT", "avg(approved - applied)", "hours", "lower_is_better")],
     [("First Data", "Omaha", "Acquirer Processor"),
      ("Worldpay", "WPG", "Acquirer Processor"),
      ("Chase", "Paymentech", "Acquirer Processor"),
      ("Adyen", "Acquiring", "Global Acquirer"),
      ("Stripe", "Connect", "Marketplace Acquiring")],
     [("ISO8583", "TCP", "PKI/MAC"),
      ("REST/Webhook", "HTTPS", "OAuth2/HMAC"),
      ("File feeds", "SFTP", "SSH key")],
     [("Merchant", "Merchant master record"),
      ("Mid", "Merchant identification number"),
      ("MerchantTransaction", "Authorized/cleared sale or refund"),
      ("Chargeback", "Chargeback case"),
      ("Settlement", "Daily settlement to merchant"),
      ("RiskScore", "Merchant risk score over time")]),

    ("asset_management", "Asset Management", "BFSI",
     "Institutional and retail asset management: portfolios, IBOR, performance, and fees.",
     [("CIO", "Chief Investment Officer", "C-suite"),
      ("Head of Performance", "Head of Performance", "Director"),
      ("Portfolio Manager", "Senior Portfolio Manager", "Manager")],
     [("am.kpi.aum", "Assets Under Management", "sum(market_value)", "USD", "higher_is_better"),
      ("am.kpi.alpha", "Alpha vs Benchmark", "return - benchmark", "bps", "higher_is_better"),
      ("am.kpi.sharpe", "Sharpe Ratio", "(return-rf)/stddev", "ratio", "higher_is_better"),
      ("am.kpi.te", "Tracking Error", "stddev(return - benchmark)", "bps", "target_band"),
      ("am.kpi.fee_yield", "Fee Yield", "fees / aum", "bps", "higher_is_better")],
     [("BlackRock", "Aladdin", "Investment Platform"),
      ("SimCorp", "Dimension", "IBOR"),
      ("Charles River", "CRD", "OMS"),
      ("FactSet", "Workstation", "Analytics"),
      ("Bloomberg", "AIM", "Order Mgmt")],
     [("REST", "HTTPS", "OAuth2"),
      ("FIX", "TCP", "TLS"),
      ("File feeds", "SFTP", "SSH key")],
     [("Portfolio", "Managed portfolio"),
      ("Holding", "Position in an instrument"),
      ("Trade", "Buy/sell instruction"),
      ("Benchmark", "Reference benchmark"),
      ("Performance", "Daily performance metrics"),
      ("Mandate", "Investment mandate definition")]),

    # ---------------- CPG ----------------
    ("brand_marketing", "Brand Marketing", "CPG",
     "Brand health tracking, integrated marketing communications, and ROI of brand investments.",
     [("CMO", "Chief Marketing Officer", "C-suite"),
      ("Brand Director", "Brand Director", "Director"),
      ("Insights Manager", "Consumer Insights Manager", "Manager")],
     [("bm.kpi.brand_awareness", "Aided Brand Awareness", "aided / surveyed", "%", "higher_is_better"),
      ("bm.kpi.share_of_voice", "Share of Voice", "brand_impressions / category", "%", "higher_is_better"),
      ("bm.kpi.media_roi", "Media ROI", "incremental_sales / spend", "ratio", "higher_is_better"),
      ("bm.kpi.npi_velocity", "NPI Sales Velocity", "sales / store_week", "USD", "higher_is_better"),
      ("bm.kpi.brand_equity_idx", "Brand Equity Index", "composite", "idx", "higher_is_better")],
     [("Nielsen", "BrandScape", "Brand Tracker"),
      ("Kantar", "Brand Tracking", "Brand Tracker"),
      ("Meta", "Ads Manager", "DSP"),
      ("Google", "Ads", "DSP"),
      ("Salesforce", "Marketing Cloud", "Campaign Mgmt")],
     [("REST", "HTTPS", "OAuth2"),
      ("File feeds", "SFTP", "SSH key"),
      ("Webhook", "HTTPS", "HMAC")],
     [("Campaign", "Marketing campaign"),
      ("Channel", "Media channel"),
      ("Spend", "Channel-level media spend"),
      ("BrandTrackerWave", "Periodic survey wave"),
      ("Reach", "Audience reach")]),

    ("retail_execution", "Retail Execution", "CPG",
     "In-store execution at the retailer: planograms, OSA, perfect store, and field rep activity.",
     [("VP Field Sales", "VP Field Sales", "VP"),
      ("KAM", "Key Account Manager", "Manager"),
      ("Field Rep", "Territory Sales Rep", "IC")],
     [("rex.kpi.osa", "On-Shelf Availability", "instock / audited", "%", "higher_is_better"),
      ("rex.kpi.planogram_compliance", "Planogram Compliance", "compliant / audited", "%", "higher_is_better"),
      ("rex.kpi.perfect_store", "Perfect Store Score", "weighted_compliance", "%", "higher_is_better"),
      ("rex.kpi.visit_completion", "Visit Completion", "completed / planned", "%", "higher_is_better"),
      ("rex.kpi.share_of_shelf", "Share of Shelf", "brand_facings / total", "%", "higher_is_better")],
     [("Salesforce", "Consumer Goods Cloud", "SFA"),
      ("Trax", "Computer Vision", "Image Recognition"),
      ("Repsly", "Field App", "Mobile Field App"),
      ("StayinFront", "TouchCG", "SFA"),
      ("Pepsico", "CrunchTime", "Field Rep App")],
     [("REST", "HTTPS", "OAuth2"),
      ("Image upload", "HTTPS", "OAuth2"),
      ("File feeds", "SFTP", "SSH key")],
     [("Outlet", "Retail outlet"),
      ("Visit", "Sales rep store visit"),
      ("Audit", "Shelf audit observation"),
      ("Planogram", "Planogram definition"),
      ("FieldRep", "Sales representative")]),

    # ---------------- Retail ----------------
    ("dark_stores", "Dark Stores", "Retail",
     "Dedicated micro-fulfilment centres serving online and quick-commerce orders.",
     [("Head of Q-Commerce", "Head of Quick Commerce", "VP"),
      ("Dark Store Manager", "Dark Store Manager", "Manager"),
      ("Pick-Pack Lead", "Pick-Pack Operations Lead", "Manager")],
     [("ds.kpi.pick_rate", "Picks per Hour", "picks / labor_hour", "picks/h", "higher_is_better"),
      ("ds.kpi.order_cycle", "Order Cycle Time", "avg(handed_off - placed)", "minutes", "lower_is_better"),
      ("ds.kpi.oos", "Out of Stock %", "oos_picks / picks", "%", "lower_is_better"),
      ("ds.kpi.subs_rate", "Substitution Rate", "substituted / picks", "%", "target_band"),
      ("ds.kpi.shrinkage", "Shrinkage", "loss / inventory", "%", "lower_is_better")],
     [("Manhattan", "Active Omni", "Order Mgmt"),
      ("Fabric", "MFC", "Micro-Fulfilment"),
      ("AutoStore", "Robotics", "Automated Storage"),
      ("Locus", "Pick by Robot", "Picking Robotics"),
      ("Bringg", "Last Mile", "Delivery Orchestration")],
     [("REST", "HTTPS", "OAuth2"),
      ("Webhook", "HTTPS", "HMAC"),
      ("File feeds", "SFTP", "SSH key")],
     [("DarkStore", "Dark store / MFC node"),
      ("Order", "Online order assigned to MFC"),
      ("Pick", "Individual pick line"),
      ("Slot", "Storage location"),
      ("Inventory", "Per-SKU per-store inventory")]),

    ("last_mile_delivery", "Last Mile Delivery", "Retail",
     "Final-mile delivery orchestration to consumer doorstep including gig and 3PL fleets.",
     [("Head of Delivery", "Head of Last-Mile Delivery", "Director"),
      ("Routing Manager", "Route Optimisation Manager", "Manager"),
      ("Driver Ops Lead", "Driver Operations Lead", "Manager")],
     [("lm.kpi.on_time", "On-Time Delivery", "on_time / total", "%", "higher_is_better"),
      ("lm.kpi.cost_per_drop", "Cost per Drop", "cost / drops", "USD", "lower_is_better"),
      ("lm.kpi.first_attempt", "First Attempt Success", "first_attempt_ok / total", "%", "higher_is_better"),
      ("lm.kpi.utilisation", "Vehicle Utilisation", "drops / capacity", "%", "higher_is_better"),
      ("lm.kpi.csat", "Delivery CSAT", "positive / responses", "%", "higher_is_better")],
     [("Bringg", "Last Mile", "Delivery Platform"),
      ("Onfleet", "Routing", "Routing"),
      ("FarEye", "Eye-On-Delivery", "Delivery Platform"),
      ("DispatchTrack", "Last Mile", "Delivery Platform"),
      ("Stuart", "Couriers", "Gig Network")],
     [("REST", "HTTPS", "OAuth2"),
      ("Webhook", "HTTPS", "HMAC"),
      ("Mobile SDK", "HTTPS", "OAuth2")],
     [("Shipment", "Outbound shipment"),
      ("Route", "Optimised driver route"),
      ("Stop", "Individual stop on a route"),
      ("Driver", "Driver / courier"),
      ("Vehicle", "Delivery vehicle"),
      ("ProofOfDelivery", "Signature/photo POD")]),

    # ---------------- TTH ----------------
    ("vacation_rentals", "Vacation Rentals", "TTH",
     "Short-term rental marketplace operations for hosts, guests, and property managers.",
     [("Head of STR", "Head of Short-Term Rentals", "VP"),
      ("Property Manager", "Property Manager", "Manager"),
      ("Trust & Safety Lead", "Trust & Safety Lead", "Manager")],
     [("vr.kpi.adr", "Average Daily Rate", "revenue / nights_sold", "USD", "higher_is_better"),
      ("vr.kpi.occupancy", "Occupancy", "nights_sold / nights_available", "%", "higher_is_better"),
      ("vr.kpi.revpar", "RevPAR", "revenue / nights_available", "USD", "higher_is_better"),
      ("vr.kpi.cancel_rate", "Cancellation Rate", "cancelled / booked", "%", "lower_is_better"),
      ("vr.kpi.host_rating", "Host Rating", "avg(rating)", "stars", "higher_is_better")],
     [("Airbnb", "Host API", "Marketplace"),
      ("VRBO", "Partner API", "Marketplace"),
      ("Booking.com", "Connectivity", "OTA"),
      ("Guesty", "PMS", "Property Mgmt"),
      ("Hostfully", "PMS", "Property Mgmt")],
     [("REST", "HTTPS", "OAuth2"),
      ("Webhook", "HTTPS", "HMAC"),
      ("File feeds", "SFTP", "SSH key")],
     [("Listing", "Rental listing"),
      ("Reservation", "Guest reservation"),
      ("Host", "Property host"),
      ("Guest", "Guest profile"),
      ("Review", "Post-stay review")]),

    ("baggage_tracking", "Baggage Tracking", "TTH",
     "End-to-end baggage handling and tracking for airlines and ground handlers.",
     [("Head of Ground Ops", "Head of Ground Operations", "Director"),
      ("Baggage Services Manager", "Baggage Services Manager", "Manager"),
      ("Lost & Found Lead", "Lost & Found Lead", "Manager")],
     [("bg.kpi.mishandled_rate", "Mishandled Baggage Rate", "mishandled / 1000_pax", "per_mille", "lower_is_better"),
      ("bg.kpi.delivery_time", "Bag Delivery Time", "avg(delivered - landed)", "minutes", "lower_is_better"),
      ("bg.kpi.lost_rate", "Lost Baggage Rate", "lost / total", "%", "lower_is_better"),
      ("bg.kpi.scan_coverage", "Bag Scan Coverage", "scanned / handled", "%", "higher_is_better"),
      ("bg.kpi.transfer_success", "Transfer Success", "made_connection / transfers", "%", "higher_is_better")],
     [("SITA", "WorldTracer", "Baggage Tracing"),
      ("Amadeus", "Altea", "DCS"),
      ("Sabre", "SabreSonic", "DCS"),
      ("BagsID", "Bag Recognition", "Computer Vision"),
      ("IATA", "Resolution 753", "Standards")],
     [("REST", "HTTPS", "OAuth2"),
      ("Type B", "Messaging", "SITA TYPE B"),
      ("File feeds", "SFTP", "SSH key")],
     [("Baggage", "Tagged baggage item"),
      ("ScanEvent", "Bag scan at a touchpoint"),
      ("Flight", "Inbound or outbound flight"),
      ("PnrLink", "Bag - PNR linkage"),
      ("MissingBagFile", "WorldTracer file")]),

    # ---------------- Manufacturing ----------------
    ("predictive_maintenance", "Predictive Maintenance", "Manufacturing",
     "ML-driven prediction of equipment failure using sensor telemetry and historical maintenance.",
     [("Head of Reliability", "Head of Reliability Engineering", "Director"),
      ("Data Science Lead", "Data Science Lead - PdM", "Manager"),
      ("Maintenance Engineer", "Sr Maintenance Engineer", "IC")],
     [("pdm.kpi.unplanned_dt", "Unplanned Downtime", "sum(unplanned_minutes)", "minutes", "lower_is_better"),
      ("pdm.kpi.precision", "Model Precision", "tp / (tp+fp)", "%", "higher_is_better"),
      ("pdm.kpi.recall", "Model Recall", "tp / (tp+fn)", "%", "higher_is_better"),
      ("pdm.kpi.mtbf", "MTBF", "operating_time / failures", "hours", "higher_is_better"),
      ("pdm.kpi.work_order_lead", "Work Order Lead Time", "alert_to_wo", "hours", "lower_is_better")],
     [("GE", "Predix", "IIoT"),
      ("PTC", "ThingWorx", "IIoT"),
      ("AVEVA", "PI System", "Historian"),
      ("Siemens", "Senseye", "PdM SaaS"),
      ("IBM", "Maximo", "EAM")],
     [("OPC-UA", "TCP", "Cert"),
      ("MQTT", "TCP", "TLS"),
      ("REST", "HTTPS", "OAuth2")],
     [("Asset", "Plant asset under maintenance"),
      ("Sensor", "Telemetry sensor"),
      ("FailureMode", "Catalogued failure mode"),
      ("ModelPrediction", "PdM model output"),
      ("WorkOrder", "Generated maintenance WO")]),

    ("supply_chain_visibility", "Supply Chain Visibility", "Manufacturing",
     "End-to-end shipment, inventory, and ETA visibility across multi-tier supplier networks.",
     [("Head of SCV", "Head of Supply Chain Visibility", "Director"),
      ("Logistics Manager", "Logistics Manager", "Manager"),
      ("Supplier Collaboration Lead", "Supplier Collaboration Lead", "Manager")],
     [("scv.kpi.eta_accuracy", "ETA Accuracy", "abs(actual - eta) <= 1d", "%", "higher_is_better"),
      ("scv.kpi.in_transit", "In-Transit Inventory", "sum(in_transit_value)", "USD", "target_band"),
      ("scv.kpi.exception_rate", "Exception Rate", "exceptions / shipments", "%", "lower_is_better"),
      ("scv.kpi.dwell_time", "Dwell Time", "avg(dwell)", "hours", "lower_is_better"),
      ("scv.kpi.tier2_visibility", "Tier-2 Visibility", "tier2_known / total", "%", "higher_is_better")],
     [("project44", "Movement", "Real-time Visibility"),
      ("FourKites", "Tracking", "Real-time Visibility"),
      ("E2open", "Harmony", "Multi-enterprise"),
      ("SAP", "IBP", "Supply Chain"),
      ("Oracle", "SCM", "Supply Chain")],
     [("REST", "HTTPS", "OAuth2"),
      ("EDI 214", "SFTP", "SSH key"),
      ("Webhook", "HTTPS", "HMAC")],
     [("Shipment", "Inbound or outbound shipment"),
      ("Milestone", "Shipment milestone event"),
      ("PurchaseOrder", "Linked PO"),
      ("Carrier", "Carrier party"),
      ("Site", "Origin/destination site")]),

    # ---------------- LifeSciences ----------------
    ("pharma_supply_chain", "Pharma Supply Chain", "LifeSciences",
     "Cold-chain, serialization, and DSCSA-compliant supply chain for pharmaceuticals.",
     [("Head of Pharma SC", "Head of Pharma Supply Chain", "VP"),
      ("Cold Chain Manager", "Cold Chain Manager", "Manager"),
      ("Serialization Lead", "Serialization Compliance Lead", "Manager")],
     [("psc.kpi.cold_chain_excursions", "Cold Chain Excursions", "excursions / shipments", "%", "lower_is_better"),
      ("psc.kpi.dscsa_coverage", "DSCSA Coverage", "compliant / total_units", "%", "higher_is_better"),
      ("psc.kpi.lot_recall_time", "Lot Recall Time", "avg(quarantine - issued)", "hours", "lower_is_better"),
      ("psc.kpi.fillrate", "Customer Order Fill Rate", "filled / ordered", "%", "higher_is_better"),
      ("psc.kpi.scrap_rate", "Scrap Rate", "scrapped / produced", "%", "lower_is_better")],
     [("SAP", "S/4HANA", "ERP"),
      ("Oracle", "SCM", "Supply Chain"),
      ("TraceLink", "Network", "Serialization"),
      ("Sensitech", "TempTale", "Cold Chain Loggers"),
      ("Antares Vision", "Track & Trace", "Serialization")],
     [("REST", "HTTPS", "OAuth2"),
      ("EPCIS", "HTTPS", "mTLS"),
      ("File feeds", "SFTP", "SSH key")],
     [("Lot", "Manufactured lot"),
      ("Serial", "Serialized unit"),
      ("ColdChainReading", "Temperature reading"),
      ("Shipment", "Pharma shipment"),
      ("Recall", "Lot recall record")]),

    # ---------------- Healthcare ----------------
    ("telehealth", "Telehealth", "Healthcare",
     "Virtual care delivery: scheduling, video visits, e-prescribing, and remote monitoring.",
     [("Head of Virtual Care", "Head of Virtual Care", "VP"),
      ("Clinical Operations Lead", "Clinical Operations Lead", "Director"),
      ("Patient Experience Manager", "Patient Experience Manager", "Manager")],
     [("th.kpi.visit_volume", "Virtual Visit Volume", "count(visits)", "visits", "higher_is_better"),
      ("th.kpi.no_show", "No-Show Rate", "no_show / scheduled", "%", "lower_is_better"),
      ("th.kpi.first_call_resolution", "First Visit Resolution", "resolved_in_one / total", "%", "higher_is_better"),
      ("th.kpi.connection_quality", "Video Connection Quality", "good_calls / total", "%", "higher_is_better"),
      ("th.kpi.csat", "Patient CSAT", "positive / responses", "%", "higher_is_better")],
     [("Teladoc", "Platform", "Telehealth"),
      ("Amwell", "Platform", "Telehealth"),
      ("Doxy.me", "Telemedicine", "Telehealth"),
      ("Epic", "Telehealth", "EHR Module"),
      ("Twilio", "Programmable Video", "CPaaS")],
     [("REST", "HTTPS", "OAuth2"),
      ("FHIR", "HTTPS", "SMART on FHIR"),
      ("Webhook", "HTTPS", "HMAC")],
     [("Visit", "Telehealth visit"),
      ("Patient", "Patient profile"),
      ("Provider", "Provider profile"),
      ("Schedule", "Provider schedule slot"),
      ("Prescription", "E-prescription order")]),

    ("medical_imaging", "Medical Imaging", "Healthcare",
     "Radiology and imaging operations: PACS, RIS, AI triage, and reporting workflow.",
     [("Chief of Radiology", "Chief of Radiology", "C-suite"),
      ("PACS Administrator", "PACS Administrator", "Manager"),
      ("Modality Tech Lead", "Modality Tech Lead", "IC")],
     [("mi.kpi.report_tat", "Report Turnaround", "avg(read - acquired)", "minutes", "lower_is_better"),
      ("mi.kpi.repeat_rate", "Repeat Imaging Rate", "repeats / studies", "%", "lower_is_better"),
      ("mi.kpi.modality_utilisation", "Modality Utilisation", "scan_minutes / available", "%", "higher_is_better"),
      ("mi.kpi.discrepancy_rate", "Read Discrepancy Rate", "discrepant / peer_reviewed", "%", "lower_is_better"),
      ("mi.kpi.ai_triage_lift", "AI Triage Lift", "critical_caught_by_ai", "%", "higher_is_better")],
     [("Sectra", "PACS", "PACS"),
      ("GE", "Centricity", "RIS/PACS"),
      ("Philips", "IntelliSpace", "PACS"),
      ("Aidoc", "Triage AI", "AI Triage"),
      ("Nuance", "PowerScribe", "Reporting")],
     [("DICOM", "DIMSE", "TLS"),
      ("HL7v2", "MLLP", "TLS"),
      ("FHIR", "HTTPS", "SMART on FHIR")],
     [("Study", "Imaging study"),
      ("Series", "Series within a study"),
      ("Modality", "Imaging modality (CT/MRI/etc.)"),
      ("Report", "Radiology report"),
      ("AiFinding", "AI-detected finding")]),

    ("patient_engagement", "Patient Engagement", "Healthcare",
     "Patient portals, messaging, reminders, and digital front-door experiences.",
     [("Chief Experience Officer", "Chief Patient Experience Officer", "C-suite"),
      ("Digital Front Door PM", "Digital Front Door Product Manager", "Manager"),
      ("Engagement Marketer", "Patient Engagement Marketer", "IC")],
     [("pe.kpi.portal_adoption", "Portal Adoption", "activated / eligible", "%", "higher_is_better"),
      ("pe.kpi.message_response", "Message Response Time", "avg(replied - sent)", "hours", "lower_is_better"),
      ("pe.kpi.reminder_success", "Reminder Success", "kept / reminded", "%", "higher_is_better"),
      ("pe.kpi.nps", "Patient NPS", "promoters - detractors", "NPS", "higher_is_better"),
      ("pe.kpi.online_scheduling", "Online Scheduling Share", "online / total", "%", "higher_is_better")],
     [("Epic", "MyChart", "Patient Portal"),
      ("Cerner", "HealtheLife", "Patient Portal"),
      ("Athenahealth", "athenaCommunicator", "Engagement"),
      ("Twilio", "Messaging", "SMS/Comms"),
      ("Salesforce", "Health Cloud", "CRM")],
     [("FHIR", "HTTPS", "SMART on FHIR"),
      ("REST", "HTTPS", "OAuth2"),
      ("Webhook", "HTTPS", "HMAC")],
     [("Patient", "Patient profile"),
      ("PortalAccount", "Linked portal account"),
      ("Message", "Secure message"),
      ("Reminder", "Appointment reminder"),
      ("Appointment", "Scheduled appointment")]),

    ("clinical_decision_support", "Clinical Decision Support", "Healthcare",
     "Evidence-based alerts and order sets at the point of care, integrated with EHR.",
     [("CMIO", "Chief Medical Information Officer", "C-suite"),
      ("Clinical Informatics Lead", "Clinical Informatics Lead", "Director"),
      ("Knowledge Engineer", "Clinical Knowledge Engineer", "IC")],
     [("cds.kpi.alert_action_rate", "Alert Action Rate", "acted / fired", "%", "higher_is_better"),
      ("cds.kpi.alert_override", "Alert Override Rate", "overridden / fired", "%", "target_band"),
      ("cds.kpi.protocol_compliance", "Protocol Compliance", "compliant / eligible", "%", "higher_is_better"),
      ("cds.kpi.harm_avoided", "Harms Avoided per 1k Visits", "harms_avoided", "per_1k", "higher_is_better"),
      ("cds.kpi.alert_latency", "Alert Latency", "avg(fired - eligible)", "ms", "lower_is_better")],
     [("Epic", "Best Practice Advisories", "CDS"),
      ("Cerner", "Discern", "CDS"),
      ("Wolters Kluwer", "UpToDate", "Reference"),
      ("Elsevier", "ClinicalKey", "Reference"),
      ("IBM", "Micromedex", "Drug Reference")],
     [("FHIR", "HTTPS", "SMART on FHIR"),
      ("CDS Hooks", "HTTPS", "OAuth2"),
      ("REST", "HTTPS", "OAuth2")],
     [("Rule", "CDS rule definition"),
      ("AlertEvent", "Fired alert"),
      ("OrderSet", "Bundled clinical order set"),
      ("ClinicalContext", "Patient context at firing time"),
      ("Outcome", "Linked clinical outcome")]),

    # ---------------- Telecom ----------------
    ("network_slicing_5g", "5G Network Slicing", "Telecom",
     "Lifecycle management of 5G network slices for enterprise SLAs and consumer use cases.",
     [("Head of 5G", "Head of 5G Programs", "VP"),
      ("Slice Architect", "5G Slice Architect", "Director"),
      ("SLA Operations", "SLA Operations Lead", "Manager")],
     [("ns.kpi.active_slices", "Active Slices", "count(active_slices)", "slices", "higher_is_better"),
      ("ns.kpi.slice_sla_met", "Slice SLA Compliance", "compliant / total", "%", "higher_is_better"),
      ("ns.kpi.provision_time", "Slice Provision Time", "avg(provisioned - requested)", "minutes", "lower_is_better"),
      ("ns.kpi.slice_arpu", "Slice ARPU", "slice_revenue / slices", "USD", "higher_is_better"),
      ("ns.kpi.contention", "Slice Contention", "contention_events", "events", "lower_is_better")],
     [("Ericsson", "Dynamic Orchestration", "5G Core"),
      ("Nokia", "CloudBand", "5G Core"),
      ("Mavenir", "MAVCore", "5G Core"),
      ("Cisco", "Crosswork", "Network Automation"),
      ("Red Hat", "OpenShift", "Cloud-Native Platform")],
     [("3GPP REST", "HTTPS", "OAuth2"),
      ("NetConf/YANG", "NetConf", "SSH"),
      ("Kafka", "Kafka", "SASL/SCRAM")],
     [("Slice", "5G network slice"),
      ("SliceTemplate", "Slice template definition"),
      ("EnterpriseTenant", "Slice consumer"),
      ("SlaContract", "Slice SLA contract"),
      ("SliceMetric", "Per-slice metric")]),

    ("video_streaming_qoe", "Video Streaming QoE", "Telecom",
     "Quality of experience for OTT video: rebuffering, startup time, and bitrate adaptation.",
     [("Head of Video QoE", "Head of Video QoE", "Director"),
      ("CDN Architect", "CDN Architect", "Manager"),
      ("Player Engineer", "Senior Player Engineer", "IC")],
     [("qoe.kpi.rebuffer_ratio", "Rebuffer Ratio", "rebuffer_time / play_time", "%", "lower_is_better"),
      ("qoe.kpi.startup_time", "Startup Time", "avg(first_frame - request)", "ms", "lower_is_better"),
      ("qoe.kpi.avg_bitrate", "Average Bitrate", "sum(bytes) / play_time", "kbps", "higher_is_better"),
      ("qoe.kpi.failure_rate", "Playback Failure Rate", "failed / attempted", "%", "lower_is_better"),
      ("qoe.kpi.exit_before_start", "Exit Before Start", "exits / starts", "%", "lower_is_better")],
     [("Conviva", "Pulse", "QoE Analytics"),
      ("NPAW", "YouMonitor", "QoE Analytics"),
      ("Akamai", "CDN", "CDN"),
      ("Fastly", "CDN", "CDN"),
      ("Mux", "Data", "Video Analytics")],
     [("REST", "HTTPS", "OAuth2"),
      ("Beacon", "HTTPS", "Token"),
      ("Webhook", "HTTPS", "HMAC")],
     [("Session", "Playback session"),
      ("PlaybackEvent", "Player event"),
      ("CdnPop", "CDN edge point"),
      ("Asset", "Video asset"),
      ("Device", "Playback device")]),

    # ---------------- Media ----------------
    ("programmatic_advertising", "Programmatic Advertising", "Media",
     "Real-time bidded ad transactions across SSPs, DSPs, and ad exchanges.",
     [("Head of Programmatic", "Head of Programmatic", "Director"),
      ("Yield Analyst", "Senior Yield Analyst", "Manager"),
      ("Ad Ops Engineer", "Ad Operations Engineer", "IC")],
     [("prog.kpi.fill_rate", "Fill Rate", "filled / requests", "%", "higher_is_better"),
      ("prog.kpi.cpm", "Effective CPM", "revenue * 1000 / impressions", "USD", "higher_is_better"),
      ("prog.kpi.viewability", "Viewability", "viewable / measurable", "%", "higher_is_better"),
      ("prog.kpi.bid_win", "Bid Win Rate", "wins / bids", "%", "target_band"),
      ("prog.kpi.ivt_rate", "Invalid Traffic Rate", "ivt / impressions", "%", "lower_is_better")],
     [("Google", "Ad Manager", "SSP/Ad Server"),
      ("Magnite", "SpringServe", "SSP"),
      ("PubMatic", "OpenWrap", "SSP"),
      ("The Trade Desk", "Platform", "DSP"),
      ("IAS", "Verification", "Ad Verification")],
     [("OpenRTB", "HTTPS", "Token"),
      ("REST", "HTTPS", "OAuth2"),
      ("S3 export", "HTTPS", "IAM")],
     [("BidRequest", "RTB bid request"),
      ("BidResponse", "RTB bid response"),
      ("Impression", "Served impression"),
      ("LineItem", "Campaign line item"),
      ("Audience", "Targeting audience segment")]),

    # ---------------- Energy / Utilities ----------------
    ("renewable_generation", "Renewable Generation", "Energy",
     "Wind, solar, and hybrid generation: forecasting, dispatch, and curtailment.",
     [("Head of Renewables", "Head of Renewables", "VP"),
      ("Forecasting Lead", "Forecasting Lead", "Manager"),
      ("Plant Operations", "Plant Operations Manager", "Manager")],
     [("rg.kpi.capacity_factor", "Capacity Factor", "actual_mwh / nameplate_max", "%", "higher_is_better"),
      ("rg.kpi.forecast_mape", "Forecast MAPE", "avg(|actual-forecast|/actual)", "%", "lower_is_better"),
      ("rg.kpi.curtailment", "Curtailment Volume", "sum(curtailed_mwh)", "MWh", "lower_is_better"),
      ("rg.kpi.availability", "Plant Availability", "up_hours / total_hours", "%", "higher_is_better"),
      ("rg.kpi.lcoe", "Levelised Cost of Energy", "cost / mwh", "USD/MWh", "lower_is_better")],
     [("GE", "Renewable Hybrid", "SCADA"),
      ("Vestas", "CMS", "Wind SCADA"),
      ("AVEVA", "PI System", "Historian"),
      ("DNV", "WindFarmer", "Forecasting"),
      ("Vaisala", "Forecast", "Weather Data")],
     [("OPC-UA", "TCP", "Cert"),
      ("DNP3", "TCP", "Mutual Auth"),
      ("REST", "HTTPS", "OAuth2")],
     [("GenerationAsset", "Wind/solar asset"),
      ("ProductionReading", "Generation telemetry"),
      ("Forecast", "Hourly generation forecast"),
      ("CurtailmentEvent", "Curtailment instruction"),
      ("Weather", "Weather observation")]),

    ("carbon_accounting", "Carbon Accounting", "Energy",
     "Scope 1/2/3 GHG accounting, sustainability reporting, and offset tracking.",
     [("Chief Sustainability Officer", "Chief Sustainability Officer", "C-suite"),
      ("Carbon Accountant", "Senior Carbon Accountant", "Manager"),
      ("ESG Reporting Lead", "ESG Reporting Lead", "Manager")],
     [("ca.kpi.scope1", "Scope 1 Emissions", "sum(direct_co2e)", "tCO2e", "lower_is_better"),
      ("ca.kpi.scope2", "Scope 2 Emissions", "sum(indirect_energy_co2e)", "tCO2e", "lower_is_better"),
      ("ca.kpi.scope3", "Scope 3 Emissions", "sum(value_chain_co2e)", "tCO2e", "lower_is_better"),
      ("ca.kpi.intensity", "Emissions Intensity", "co2e / revenue", "kg/USD", "lower_is_better"),
      ("ca.kpi.offset_coverage", "Offset Coverage", "offsets / emissions", "%", "higher_is_better")],
     [("Microsoft", "Sustainability Manager", "ESG Platform"),
      ("Salesforce", "Net Zero Cloud", "ESG Platform"),
      ("Persefoni", "Climate Disclosure", "Carbon Platform"),
      ("Watershed", "Platform", "Carbon Platform"),
      ("Sphera", "Sustainability", "ESG Platform")],
     [("REST", "HTTPS", "OAuth2"),
      ("File feeds", "SFTP", "SSH key"),
      ("Webhook", "HTTPS", "HMAC")],
     [("EmissionFactor", "Emission factor lookup"),
      ("Activity", "Emission-causing activity"),
      ("EmissionEvent", "Calculated emission record"),
      ("Offset", "Carbon offset purchase"),
      ("Disclosure", "Periodic regulatory disclosure")]),

    ("gas_distribution", "Gas Distribution", "Utilities",
     "Natural gas distribution, leak detection, odorization, and customer service.",
     [("Head of Gas Distribution", "Head of Gas Distribution", "VP"),
      ("Pipeline Integrity Lead", "Pipeline Integrity Manager", "Manager"),
      ("Field Ops Supervisor", "Field Operations Supervisor", "Manager")],
     [("gd.kpi.leak_response_time", "Leak Response Time", "avg(arrival - reported)", "minutes", "lower_is_better"),
      ("gd.kpi.lost_unaccounted", "Lost & Unaccounted For", "unaccounted / sent_out", "%", "lower_is_better"),
      ("gd.kpi.dimp_compliance", "DIMP Compliance", "compliant_segments / total", "%", "higher_is_better"),
      ("gd.kpi.odorization_failures", "Odorization Failures", "fail_count", "incidents", "lower_is_better"),
      ("gd.kpi.locate_tickets", "Locate Tickets Closed On Time", "on_time / total", "%", "higher_is_better")],
     [("Schneider", "ClearSCADA", "SCADA"),
      ("Itron", "Endpoint", "Gas Meter"),
      ("Esri", "Utility Network", "GIS"),
      ("Picarro", "Surveyor", "Leak Detection"),
      ("OpenText", "Damage Prevention", "Locate Tickets")],
     [("DNP3", "TCP", "Mutual Auth"),
      ("Modbus", "TCP", "Cert"),
      ("REST", "HTTPS", "OAuth2")],
     [("PipelineSegment", "Distribution pipeline segment"),
      ("LeakReport", "Reported leak"),
      ("InspectionRecord", "Pipeline inspection record"),
      ("ServiceOrder", "Customer service order"),
      ("OdorizationReading", "Odorant level reading")]),

    ("water_utilities", "Water Utilities", "Utilities",
     "Water distribution: treatment, metering, non-revenue water, and quality compliance.",
     [("Head of Water Operations", "Head of Water Operations", "VP"),
      ("Distribution Engineer", "Distribution Engineer", "Manager"),
      ("Water Quality Lead", "Water Quality Lead", "Manager")],
     [("wu.kpi.nrw", "Non-Revenue Water", "(produced - billed)/produced", "%", "lower_is_better"),
      ("wu.kpi.compliance", "Quality Compliance", "compliant_samples / total", "%", "higher_is_better"),
      ("wu.kpi.main_breaks", "Main Breaks per 100mi", "breaks / 100mi", "incidents", "lower_is_better"),
      ("wu.kpi.pressure_excursions", "Pressure Excursions", "out_of_range / readings", "%", "lower_is_better"),
      ("wu.kpi.amr_coverage", "AMR/AMI Coverage", "smart_meters / total", "%", "higher_is_better")],
     [("Itron", "Riva", "AMI"),
      ("Sensus", "FlexNet", "AMI"),
      ("Schneider", "AVEVA Water", "SCADA"),
      ("Esri", "Utility Network", "GIS"),
      ("HydroIQ", "Water Network", "Smart Water")],
     [("DNP3", "TCP", "Mutual Auth"),
      ("REST", "HTTPS", "OAuth2"),
      ("File feeds", "SFTP", "SSH key")],
     [("WaterMeter", "Water meter"),
      ("MeterRead", "Periodic meter read"),
      ("Sample", "Water quality sample"),
      ("MainBreak", "Distribution main break event"),
      ("Sensor", "Pressure / flow sensor")]),

    # ---------------- PublicSector ----------------
    ("emergency_response", "Emergency Response", "PublicSector",
     "911 dispatch, incident management, and inter-agency coordination for emergency services.",
     [("Director of EMS", "Director of Emergency Medical Services", "Director"),
      ("Dispatch Center Manager", "Dispatch Center Manager", "Manager"),
      ("Field Commander", "Field Commander", "Manager")],
     [("er.kpi.response_time", "Response Time", "avg(arrived - dispatched)", "minutes", "lower_is_better"),
      ("er.kpi.dispatch_time", "Dispatch Time", "avg(dispatched - received)", "seconds", "lower_is_better"),
      ("er.kpi.unit_availability", "Unit Availability", "available_minutes / total", "%", "higher_is_better"),
      ("er.kpi.priority1_compliance", "Priority-1 SLA Compliance", "met / total", "%", "higher_is_better"),
      ("er.kpi.cad_to_rms", "CAD-to-RMS Latency", "avg(rms_ts - cad_ts)", "seconds", "lower_is_better")],
     [("Hexagon", "CAD", "CAD"),
      ("Tyler", "New World", "CAD/RMS"),
      ("Motorola", "CommandCentral", "CAD"),
      ("RapidSOS", "NG911", "NG911 Data"),
      ("Esri", "ArcGIS", "GIS")],
     [("REST", "HTTPS", "OAuth2"),
      ("CAP", "XML/HTTPS", "Cert"),
      ("File feeds", "SFTP", "SSH key")],
     [("Incident", "911 incident"),
      ("Unit", "Responding unit"),
      ("DispatchEvent", "Status change event"),
      ("Call", "Inbound 911 call"),
      ("Address", "Geocoded incident address")]),

    ("transit_operations", "Transit Operations", "PublicSector",
     "Public transit operations: scheduling, real-time vehicle telemetry, and service alerts.",
     [("Director of Transit Operations", "Director of Transit Operations", "Director"),
      ("Service Planning Lead", "Service Planning Lead", "Manager"),
      ("Operations Control Center", "OCC Supervisor", "Manager")],
     [("to.kpi.on_time", "On-Time Performance", "on_time / arrivals", "%", "higher_is_better"),
      ("to.kpi.headway_adherence", "Headway Adherence", "within_band / observations", "%", "higher_is_better"),
      ("to.kpi.ridership", "Daily Ridership", "sum(boardings)", "passengers", "higher_is_better"),
      ("to.kpi.miles_per_breakdown", "Miles per Breakdown", "miles / breakdowns", "miles", "higher_is_better"),
      ("to.kpi.crowding", "Vehicle Crowding", "crowded_trips / trips", "%", "lower_is_better")],
     [("Trapeze", "FX", "Scheduling"),
      ("INIT", "MOBILE", "ITS"),
      ("Cubic", "NextBus", "Real-time Info"),
      ("Conduent", "Fare", "Fare Collection"),
      ("Swiftly", "Transit", "Transit Analytics")],
     [("GTFS-RT", "HTTPS", "Token"),
      ("REST", "HTTPS", "OAuth2"),
      ("Kafka", "Kafka", "SASL/SCRAM")],
     [("Route", "Transit route"),
      ("Trip", "Scheduled trip"),
      ("Vehicle", "Transit vehicle"),
      ("Stop", "Boarding stop"),
      ("StopEvent", "Vehicle arrival/departure event")]),

    # ---------------- HiTech ----------------
    ("chip_design_eda", "Chip Design (EDA)", "HiTech",
     "Semiconductor design flows: RTL, simulation, synthesis, P&R, and tapeout.",
     [("VP Engineering", "VP Silicon Engineering", "VP"),
      ("Design Lead", "Senior ASIC Design Lead", "Manager"),
      ("Verification Engineer", "Senior Verification Engineer", "IC")],
     [("eda.kpi.coverage", "Functional Coverage", "covered_bins / total", "%", "higher_is_better"),
      ("eda.kpi.regression_pass", "Regression Pass Rate", "pass / runs", "%", "higher_is_better"),
      ("eda.kpi.tapeout_slippage", "Tapeout Slippage", "actual - planned", "days", "lower_is_better"),
      ("eda.kpi.bug_density", "Bug Density", "bugs / kloc", "bugs/kLOC", "lower_is_better"),
      ("eda.kpi.tool_utilisation", "EDA Tool Utilisation", "used_hours / licensed", "%", "higher_is_better")],
     [("Cadence", "Genus", "Synthesis"),
      ("Synopsys", "VCS", "Simulation"),
      ("Siemens", "Questa", "Verification"),
      ("Cadence", "Innovus", "Place & Route"),
      ("Ansys", "RedHawk", "Power Integrity")],
     [("REST", "HTTPS", "OAuth2"),
      ("File feeds", "SFTP", "SSH key"),
      ("ODBC", "TCP", "DB cred")],
     [("Project", "Chip design project"),
      ("Block", "RTL block under design"),
      ("RegressionRun", "Verification regression run"),
      ("Bug", "Tracked bug"),
      ("ToolLicenseUse", "License usage record")]),

    ("developer_relations", "Developer Relations", "HiTech",
     "Developer engagement: docs, SDKs, sample apps, and community programs to drive adoption.",
     [("Head of DevRel", "Head of Developer Relations", "Director"),
      ("Docs Lead", "Developer Docs Lead", "Manager"),
      ("Developer Advocate", "Developer Advocate", "IC")],
     [("dr.kpi.active_devs", "Monthly Active Developers", "unique_active_devs", "devs", "higher_is_better"),
      ("dr.kpi.api_call_growth", "API Call Growth (MoM)", "this_month / last_month - 1", "%", "higher_is_better"),
      ("dr.kpi.docs_satisfaction", "Docs Satisfaction", "positive / responses", "%", "higher_is_better"),
      ("dr.kpi.time_to_first_call", "Time to First API Call", "avg(first_call - signup)", "minutes", "lower_is_better"),
      ("dr.kpi.community_resolution", "Community Question Resolution", "resolved / asked", "%", "higher_is_better")],
     [("GitHub", "Discussions", "Community"),
      ("Discourse", "Forum", "Community"),
      ("Algolia", "DocSearch", "Docs Search"),
      ("Mixpanel", "Product Analytics", "Analytics"),
      ("Stripe", "API Reference", "Docs Pattern")],
     [("REST", "HTTPS", "OAuth2"),
      ("Webhook", "HTTPS", "HMAC"),
      ("S3 export", "HTTPS", "IAM")],
     [("Developer", "Registered developer"),
      ("ApiKey", "Issued API key"),
      ("ApiCall", "API call event"),
      ("DocsPage", "Documentation page"),
      ("CommunityThread", "Community thread")]),

    # ---------------- ProfessionalServices ----------------
    ("legal_case_management", "Legal Case Management", "ProfessionalServices",
     "Matter management for law firms and legal departments: intake, conflicts, and time capture.",
     [("Managing Partner", "Managing Partner", "C-suite"),
      ("General Counsel", "General Counsel", "VP"),
      ("Practice Group Lead", "Practice Group Lead", "Director")],
     [("lcm.kpi.realisation", "Realisation Rate", "collected / standard_billable", "%", "higher_is_better"),
      ("lcm.kpi.utilisation", "Lawyer Utilisation", "billable_hours / available", "%", "higher_is_better"),
      ("lcm.kpi.cycle_time", "Matter Cycle Time", "avg(closed - opened)", "days", "lower_is_better"),
      ("lcm.kpi.wip", "Work in Progress", "sum(unbilled)", "USD", "target_band"),
      ("lcm.kpi.nps", "Client NPS", "promoters - detractors", "NPS", "higher_is_better")],
     [("Aderant", "Expert", "Legal PMS"),
      ("Elite", "3E", "Legal PMS"),
      ("iManage", "Work", "Document Mgmt"),
      ("NetDocuments", "NetDocs", "Document Mgmt"),
      ("Intapp", "Open", "Conflicts/Risk")],
     [("REST", "HTTPS", "OAuth2"),
      ("File feeds", "SFTP", "SSH key"),
      ("ODBC", "TCP", "DB cred")],
     [("Matter", "Legal matter"),
      ("Client", "Client party"),
      ("TimeEntry", "Billable time entry"),
      ("Document", "Linked document"),
      ("ConflictCheck", "Conflict-check result")]),

    ("audit_workflow", "Audit Workflow", "ProfessionalServices",
     "External and internal audit engagements with risk assessment, sampling, and reporting.",
     [("Audit Partner", "Audit Partner", "C-suite"),
      ("Audit Manager", "Audit Engagement Manager", "Manager"),
      ("Senior Auditor", "Senior Auditor", "IC")],
     [("aw.kpi.engagement_realisation", "Engagement Realisation", "collected / budget", "%", "higher_is_better"),
      ("aw.kpi.sample_coverage", "Sample Coverage", "sampled / population_in_scope", "%", "higher_is_better"),
      ("aw.kpi.findings_density", "Findings per Engagement", "findings / engagements", "findings", "target_band"),
      ("aw.kpi.timeliness", "Audit Timeliness", "on_time / total", "%", "higher_is_better"),
      ("aw.kpi.review_notes", "Review Notes Per Engagement", "review_notes / engagements", "notes", "target_band")],
     [("Wolters Kluwer", "CCH Axcess", "Audit Suite"),
      ("Thomson Reuters", "AdvanceFlow", "Audit Suite"),
      ("Deloitte", "Omnia", "Audit Suite"),
      ("MindBridge", "AI Auditor", "Anomaly Detection"),
      ("Caseware", "Cloud", "Audit Suite")],
     [("REST", "HTTPS", "OAuth2"),
      ("File feeds", "SFTP", "SSH key"),
      ("ODBC", "TCP", "DB cred")],
     [("Engagement", "Audit engagement"),
      ("Workpaper", "Audit workpaper"),
      ("Finding", "Audit finding"),
      ("Sample", "Sampled item"),
      ("Risk", "Risk register entry")]),
]


def emit_yaml(rec):
    (sub_id, name, vertical, oneliner, personas, kpis, sources, conns, entities) = rec
    lines = []
    lines.append(f"id: {sub_id}")
    lines.append(f"name: {name}")
    lines.append(f"vertical: {vertical}")
    lines.append(f"oneLiner: {oneliner}")
    lines.append("")
    lines.append("personas:")
    for n, t, lvl in personas:
        lines.append(f"  - {{ name: {n!r}, title: {t!r}, level: {lvl} }}")
    lines.append("")
    lines.append("kpis:")
    for kid, knm, kf, ku, kdir in kpis:
        lines.append(
            f"  - {{ id: {kid}, name: {knm!r}, formula: {kf!r}, unit: {ku!r}, direction: {kdir} }}"
        )
    lines.append("")
    lines.append("dataModel:")
    lines.append("  entities:")
    for ename, edesc in entities:
        lines.append(f"    - {{ name: {ename}, description: {edesc!r} }}")
    lines.append("")
    lines.append("sourceSystems:")
    for vendor, product, cat in sources:
        lines.append(f"  - {{ vendor: {vendor!r}, product: {product!r}, category: {cat!r} }}")
    lines.append("")
    lines.append("connectors:")
    for ct, cp, ca in conns:
        lines.append(f"  - {{ type: {ct!r}, protocol: {cp!r}, auth: {ca!r} }}")
    lines.append("")
    return "\n".join(lines)


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    written = 0
    for rec in NEW:
        sub_id = rec[0]
        path = OUT / f"{sub_id}.yaml"
        path.write_text(emit_yaml(rec), encoding="utf-8")
        written += 1
    print(f"wrote {written} files to {OUT}")


if __name__ == "__main__":
    main()
