name: domain_explorer
version: 1.0.0
config-version: 2

profile: domain_explorer

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: target
clean-targets:
  - target
  - dbt_packages

models:
  domain_explorer:
    +schema: dbt
    payments:
      staging:
        +materialized: view
      intermediate:
        +materialized: ephemeral
      marts:
        +materialized: table
    p_and_c_claims:
      staging:
        +materialized: view
      intermediate:
        +materialized: ephemeral
      marts:
        +materialized: table
    merchandising:
      staging:
        +materialized: view
      intermediate:
        +materialized: ephemeral
      marts:
        +materialized: table
    demand_planning:
      staging:
        +materialized: view
      intermediate:
        +materialized: ephemeral
      marts:
        +materialized: table
    hotel_revenue_management:
      staging:
        +materialized: view
      intermediate:
        +materialized: ephemeral
      marts:
        +materialized: table
